// Auto-extracted constants from resume.ts

export const ALL_SKILLS: string[] = [
    ".NET Core",
    "1-on-1 Mentoring",
    "3D Math & Linear Algebra",
    "A/B Testing",
    "A/B Testing design & execution",
    "ADB command line",
    "AI Agents",
    "AI Ethics",
    "AI Product Management",
    "AI Research",
    "AI Roadmapping",
    "AI Safety",
    "AJAX",
    "API Developer Portal",
    "API Documentation",
    "API Documentation (OpenAPI/Swagger)",
    "API Gateway (Kong/Apigee)",
    "API Gateway design",
    "API Integration",
    "API Integration strategy",
    "API Platform Engineering",
    "API Routes",
    "API Testing",
    "API Testing (Postman/RestAssured)",
    "ARM Cortex",
    "ARM Templates",
    "ASP.NET MVC",
    "AWS",
    "AWS DynamoDB",
    "AWS ECS",
    "AWS EKS",
    "AWS IAM",
    "AWS IAM Roles governance",
    "AWS Lambda",
    "AWS Route53",
    "AWS/Azure Cloud security",
    "AWS/Azure/GCP",
    "Academic Writing",
    "Account Management",
    "Accounts Payable/Receivable",
    "Activation Funnel optimization",
    "Active Directory",
    "Active Directory Administration",
    "ActiveRecord",
    "Actix-web",
    "Ad Copy creation",
    "Adaptability",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Adobe Photoshop",
    "Adobe Photoshop & Illustrator",
    "Adobe XD",
    "Agile",
    "Agile Delivery",
    "Agile Maturity Assessment",
    "Agile Methodologies",
    "Agile Principles",
    "Agile Testing",
    "Agile Transformation",
    "Agile coaching",
    "Agile metrics tracking",
    "Agile/Scrum",
    "Agile/Scrum Management",
    "Agile/Waterfall",
    "Airflow",
    "Algorithms",
    "Algorithms Design",
    "Amazon EC2",
    "Amazon RDS",
    "Amazon S3",
    "Amazon VPC",
    "Analytical Thinking",
    "Android Deployment",
    "Android SDK",
    "Android Studio",
    "Angular",
    "Angular/React Core",
    "Ansible",
    "Apache",
    "Apache Airflow scheduling",
    "Apache JMeter testing scripts",
    "Apache Spark",
    "Apex Triggers",
    "Apigee Policies",
    "App Store Connect",
    "Appium",
    "Appium Mobile Automation",
    "Applicant Tracking Systems (ATS)",
    "Application Portfolio Management",
    "Application Security",
    "Application Security Audits",
    "Architectural Styles",
    "Arduino",
    "Assembly",
    "Assembly Language",
    "Asset Pipeline integration",
    "Async Rust",
    "Async/Await",
    "Asyncio",
    "Attribution Modeling",
    "Audit Methodology",
    "Audit Report Writing",
    "Aura Components",
    "Automation",
    "Automation Test development",
    "Axios",
    "Azure",
    "Azure AD",
    "Azure Active Directory",
    "Azure App Services",
    "Azure Blob Storage",
    "Azure DevOps",
    "Azure Functions",
    "Azure Kubernetes Service",
    "Azure SQL",
    "Azure Virtual Machines",
    "B2B Sales",
    "BERT",
    "BGP/OSPF",
    "BI Development",
    "BI Tools",
    "BI reporting integrations",
    "Babel",
    "Backend Architecture",
    "Backup & Recovery",
    "Backups",
    "Balance Sheet reconciliation",
    "Bank Reconciliation",
    "Bare-Metal Programming",
    "Bare-metal",
    "Bare-metal Programming",
    "Bash Scripting",
    "Batch Job Scheduling",
    "BeautifulSoup",
    "Benefits Administration",
    "Big Data Architecture",
    "BigQuery",
    "Blazor",
    "Bloc State Management",
    "Blockchain Protocol Development",
    "Blockchain Protocols",
    "Blogging",
    "Blueprint diagrams",
    "Blueprints Visual Scripting",
    "Boost",
    "Bootloaders",
    "Brand Assets Creation",
    "Brand Engagement",
    "Brand Identity Design",
    "Brand Storytelling",
    "Brand Strategy",
    "Brand Voice alignment",
    "Branding",
    "Browser Rendering Path",
    "Budget Administration",
    "Budget Allocation",
    "Budget Allocation & Planning",
    "Budget Management",
    "Budget Planning",
    "Budgeting & Forecasting",
    "Bug Tracking",
    "Bug reporting",
    "Bundler",
    "Burndown Charts",
    "Burp Suite",
    "Business Analytics",
    "Business Continuity Planning (BCP)",
    "Business IT Alignment",
    "Business Intelligence",
    "Business Process Mapping",
    "Business Process Modeling (BPMN)",
    "Business Systems Implementation",
    "BusinessObjects",
    "Buyer Personas",
    "C",
    "C#",
    "C# Programming",
    "C++",
    "C++ Coding Standards",
    "C++ Game Programming",
    "CI/CD",
    "CI/CD Integration",
    "CI/CD Pipelines",
    "CI/CD Security controls",
    "CI/CD for Frontend",
    "CI/CD for ML",
    "CICS Transaction processing",
    "CMake",
    "CNNs",
    "COBIT",
    "COBOL Programming",
    "CRM Integration (Salesforce)",
    "CRM Tools (Salesforce)",
    "CSS Architectures",
    "CSS3",
    "CUDA",
    "Caching Strategies (Redis)",
    "Campaign Analytics",
    "Candidate Sourcing",
    "Capistrano",
    "Card Sorting",
    "Career growth Mentoring",
    "Cargo",
    "Cassandra",
    "Celery",
    "Chain-of-Thought",
    "Change Management",
    "Channels",
    "Chaos Engineering",
    "ChromaDB",
    "Churn reduction",
    "Circuit Design",
    "Cisco Routing & Switching",
    "Clang",
    "Clean Coding",
    "Client Acquisition",
    "Client Onboarding",
    "Client Relations",
    "Client Relationships",
    "Client Retention",
    "Cloud Compliance auditing",
    "Cloud Computing",
    "Cloud Data Lakes",
    "Cloud Functions",
    "Cloud Integration",
    "Cloud Migration",
    "Cloud Migration Planning",
    "Cloud SQL",
    "Cloud Security",
    "Cloud Security Architecture",
    "CloudFormation",
    "CloudTrail auditing",
    "CloudWatch",
    "Coaching Leadership",
    "Coaching Teams",
    "Cocoa Touch",
    "CocoaPods",
    "Cocos2d",
    "Code Optimization",
    "Code Reviews",
    "CodeIgniter",
    "Cold Outreach",
    "Collibra",
    "Color Matching",
    "Color Theory",
    "Combine Framework",
    "Community Management",
    "Competitive Analysis",
    "Complex System design",
    "Compliance (ISO 27001, SOC2)",
    "Compliance (ISO/SOC2)",
    "Compliance Monitoring",
    "Compliance Standards",
    "Component Design",
    "Composer",
    "Composition API",
    "Computer Vision",
    "Concurrency",
    "Conflict Resolution",
    "Confluence",
    "Consensus Algorithms",
    "Container Vulnerability scanning (Trivy)",
    "Containerization",
    "Content Audit",
    "Content Calendar Management",
    "Content Creation",
    "Content Distribution",
    "Content Ideation",
    "Content Inventory",
    "Content Marketing",
    "Content Modeling",
    "Content Strategy Development",
    "Control Systems",
    "Conversion Rate Optimization (CRO)",
    "Convex Optimization",
    "Convolutional Neural Networks (CNN)",
    "Copywriting",
    "Core Animation",
    "Core Data",
    "Core Web Vitals",
    "Core codebase architecture",
    "Core codebase ownership",
    "Coroutines",
    "Corporate Branding",
    "Corporate Finance",
    "Cost Optimization",
    "CouchDB",
    "Crash Logs analysis",
    "Creative Briefs",
    "Crisis Communication",
    "Critical Thinking",
    "Cross-Browser Testing",
    "Cross-functional Advocacy",
    "Cross-functional Collaboration",
    "Cross-functional Leadership",
    "Cross-functional collaboration",
    "Cross-functional workshops facilitation",
    "Cryptography",
    "Cucumber",
    "Cupertino Widgets",
    "Customer Case Studies",
    "Customer Communication",
    "Customer Feedback loops",
    "Customer Interviews",
    "Customer Journey Mapping",
    "Customer Retention",
    "Customer Satisfaction (CSAT)",
    "Customer Success",
    "Cybersecurity",
    "Cybersecurity Basics",
    "Cypress",
    "DAO Infrastructure",
    "DAX",
    "DB2 Mainframe databases",
    "DITA/XML",
    "DNS/DHCP Configuration",
    "DO-178C/ISO 26262 Compliance",
    "DOM Manipulation",
    "DVC",
    "Dagger Hilt",
    "Daily Standups",
    "Dart",
    "Dashboard Design",
    "Dashboards",
    "Data Access governance",
    "Data Analytics",
    "Data Architecture",
    "Data Catalog tools management",
    "Data Cleaning",
    "Data Cleaning & validations",
    "Data Cleansing",
    "Data Compliance policies (HIPAA/GDPR)",
    "Data Drift",
    "Data Governance",
    "Data Ingestion",
    "Data Ingestion pipelines",
    "Data Lakehouse",
    "Data Lineage",
    "Data Lineage tracing",
    "Data Modeling",
    "Data Privacy Audits",
    "Data Privacy Compliance",
    "Data Privacy Impact Assessments (DPIA)",
    "Data Privacy Policies creation",
    "Data Privacy compliance",
    "Data Quality Standards definition",
    "Data Querying",
    "Data Structures",
    "Data Transformations",
    "Data Visualization",
    "Data Warehouse",
    "Data Warehouse Architecture",
    "Data Warehousing",
    "Data breach incident management",
    "Database Administration",
    "Database Design",
    "Database Indexes",
    "Database Mirroring",
    "Database Partitioning",
    "Database Replication",
    "Database Tuning",
    "Databricks",
    "Dataset Curation",
    "DeFi",
    "DeFi Hack analysis",
    "DeFi Protocols",
    "Debugging",
    "Decentralized Apps (dApps)",
    "Decorators",
    "Deep Learning",
    "Delivery Management",
    "Dependency Mapping",
    "Design Patterns",
    "Design Systems",
    "Design Thinking",
    "Design to Development Handoff",
    "DevSecOps Pipeline implementation",
    "Developer Guides",
    "Developer Mentoring",
    "Device Drivers",
    "Digital Assets",
    "Digital Forensics",
    "Digital Marketing Strategy",
    "Digital Marketing campaigns",
    "Dimensional Modeling",
    "Directory Services",
    "Disaster Recovery",
    "Disaster Recovery (DR)",
    "Disaster Recovery Planning",
    "Distributed Systems",
    "Django",
    "Docker",
    "Doctrine",
    "Dynamic Code Analysis (DAST)",
    "DynamoDB",
    "E-commerce Store Operations",
    "ELK Stack",
    "ERC20 & ERC721 Standards",
    "ERD",
    "ERP Systems (SAP/Oracle)",
    "ES6+",
    "ESLint",
    "ESNext",
    "ETL",
    "ETL Pipelines",
    "ETL Process development",
    "ETL pipeline development",
    "Echidna fuzzing",
    "Echo",
    "Edge Computing",
    "Editor skills",
    "Elasticsearch",
    "Elementor/Gutenberg custom blocks",
    "Email Campaign Setup",
    "Email Campaigns",
    "Email Marketing campaigns",
    "Embedded C",
    "Embedded Software",
    "Embedded Systems",
    "Employee Engagement",
    "Employee Relations",
    "Employee handbook creation",
    "Employer Branding",
    "EnCase",
    "Encryption Key Management (KMS)",
    "Endpoint Detection & Response (EDR)",
    "Endpoint Protection",
    "Engineering Best practices mentoring",
    "Engineering Team Leadership",
    "Enterprise Architecture Frameworks (TOGAF)",
    "Enterprise Architecture Planning",
    "Enterprise Client Support",
    "Enterprise Data Model",
    "Enterprise Design Patterns",
    "Enterprise Integration",
    "Enterprise Security",
    "Enterprise Solutions Architecture",
    "Entity Framework",
    "Ethereum",
    "Ethereum Blockchain",
    "Ethereum Virtual Machine (EVM)",
    "Ethers.js",
    "Ethical Hacking",
    "Event-Driven Architecture (Kafka)",
    "Excel",
    "Excel (VBA)",
    "Expo",
    "Express.js",
    "FMLA compliance",
    "Facilitating Agile events",
    "FastAPI",
    "Fastlane",
    "Feasibility Study",
    "Feature Engineering",
    "Feature Prioritization",
    "Feature Store",
    "Few-Shot Learning",
    "Figma",
    "Figma design layouts",
    "Figma wireframes",
    "Figma wireframes review",
    "Financial Auditing",
    "Financial Audits coordination",
    "Financial Control",
    "Financial Modeling",
    "Financial Reporting",
    "Fine-Tuning Prompts",
    "Firebase App Distribution setup",
    "Firebase Integration",
    "Firewall Auditing",
    "Firewall Rules management",
    "Firewalls",
    "Firmware Debugging",
    "Firmware Development",
    "Flask",
    "Flexbox",
    "Flume",
    "Flutter",
    "Flutter CLI",
    "Forensic Toolkits (FTK)",
    "Formal Verification",
    "Frontend Architecture",
    "GAAP/IFRS Compliance",
    "GAAP/IFRS Principles",
    "GCP",
    "GCP IAM",
    "GCP VPC",
    "GDB",
    "GDPR/CCPA frameworks implementation",
    "GPU Computing (CUDA)",
    "GRC",
    "Game AI",
    "Game Physics",
    "Game Programming",
    "Gantt Charts",
    "Gap Analysis",
    "Gas Optimization",
    "General Ledger",
    "General Ledger Accounting",
    "Generative AI",
    "Generative Adversarial Networks (GAN)",
    "Generics",
    "Gensim",
    "Gin",
    "Git",
    "Git & GitHub",
    "Git version control",
    "Git/Perforce",
    "GitHub Actions",
    "GitLab CI",
    "Go",
    "Go (Golang)",
    "Go modules",
    "Go-To-Market (GTM) Strategy",
    "Google Ads",
    "Google Analytics",
    "Google Cloud Run",
    "Google Cloud Storage",
    "Google Compute Engine",
    "Google Kubernetes Engine",
    "Google Play Console",
    "Google Search Console",
    "Goroutines",
    "Governance Frameworks",
    "Gradle",
    "Grafana",
    "Graph Databases",
    "GraphQL",
    "GraphQL Federation",
    "Graphic Design",
    "Grid Layout",
    "Growth Hacking Methodology",
    "HAL (Hardware Abstraction Layer)",
    "HBase",
    "HIPAA Compliance",
    "HR Generalist",
    "HR Metrics",
    "HR Policies",
    "HRIS (Workday/BambooHR)",
    "HRIS Software",
    "HTML5",
    "HTML5 & CSS3",
    "HTML5 & CSS3 styling",
    "HTTP Response codes analysis",
    "Hadoop",
    "Hardware Debugging",
    "Hardware Interfacing",
    "Hardware repair",
    "Hardware-Software Integration",
    "Hashtag Strategy",
    "Headhunting",
    "Helm",
    "Helpdesk Team coordination",
    "Heroku",
    "Heuristic Evaluation",
    "Hibernate",
    "High Availability",
    "Hive",
    "HubSpot / Marketo",
    "Hugging Face",
    "Human Resources",
    "Hyperledger Fabric",
    "Hyperparameter Tuning",
    "IAM",
    "IAM Governance",
    "IBM z/OS environment",
    "IDS/IPS",
    "IDS/IPS Logging",
    "IIS",
    "IPFS",
    "ISO 27001",
    "IT Asset Tracking Management",
    "IT Budget Planning & Strategy",
    "IT Desktop Support",
    "IT Infrastructure Management",
    "IT Infrastructure Projects",
    "IT Operations Governance",
    "IT PMO",
    "IT Service Management (ITSM)",
    "IT Strategy Planning",
    "ITIL Framework",
    "Illustration",
    "Image Processing",
    "Image Segmentation",
    "Incident Command",
    "Incident Escalation",
    "Incident Management",
    "Incident Reporting",
    "Incident Response",
    "Incident Response management",
    "Incremental Static Regeneration (ISR)",
    "Index Optimization",
    "Influencer Collaboration",
    "Informatica PowerCenter / Talend",
    "Information Architecture",
    "Information Security Strategy",
    "Information Systems Security",
    "Infrastructure as Code",
    "Instructional Design",
    "Integration Architectures design",
    "Integration Testing",
    "Integration testing",
    "Interaction Design",
    "Interactive Prototyping",
    "Interfaces",
    "Internal Auditing",
    "Internal Controls",
    "Interviewing Techniques",
    "Intrusion Detection",
    "Intrusion Detection/Prevention (IDS/IPS)",
    "Inventory Control",
    "IoT Architecture",
    "IoT Protocols",
    "IoT Security",
    "JAX",
    "JCL Scripting",
    "JDBC",
    "JPA",
    "JSON",
    "JSON Document Databases",
    "JSON Schema verification",
    "JTAG debugging",
    "JUnit",
    "Java",
    "JavaScript",
    "JavaScript programming",
    "Jenkins",
    "Jest",
    "Jetpack Compose",
    "Jira",
    "Jira Service Desk",
    "Jira/Confluence",
    "Jira/Git",
    "Job Posting",
    "Jupyter",
    "Jupyter Notebooks",
    "KPI Dashboards",
    "KPI Metrics Reporting",
    "KPI Tracking",
    "Kafka",
    "Kali Linux",
    "Kanban Board Setup",
    "Keil MDK",
    "Keras",
    "Kerberos",
    "Keyword Research",
    "Kinematics",
    "Knowledge Base articles",
    "Knowledge Base creation",
    "Kong Plugins",
    "Kotlin",
    "Kubeflow",
    "Kubernetes",
    "LINQ",
    "LLMs",
    "LaTeX",
    "Labor Law Compliance",
    "Labor Laws Compliance",
    "Landing Page Copy",
    "LangChain",
    "Laravel",
    "Large Language Models (LLMs)",
    "Launch Management",
    "Layout Design",
    "Lead Generation",
    "Lead Scoring",
    "Leadership",
    "LiDAR",
    "Lightning Web Components (LWC)",
    "Link Building",
    "Linting & Testing Standards",
    "Linux",
    "Linux (RedHat/Ubuntu)",
    "Linux Command Line",
    "LlamaIndex",
    "Load Balancing",
    "Load, Stress & Soak testing",
    "LoadRunner enterprise tools",
    "Local SEO",
    "Lodash",
    "Log Analysis",
    "Logic Analyzers",
    "Logic Building",
    "Logo Design",
    "MDX",
    "MLOps",
    "MLflow",
    "MQTT/CoAP",
    "MS Project",
    "MVC Architecture",
    "MVC/MVVM",
    "MVVM Architecture",
    "Machine Learning",
    "Machine Learning Lifecycle",
    "MadCap Flare",
    "Mainframe Troubleshooting",
    "Manual QA methodologies",
    "Manual Testing",
    "MapReduce",
    "Markdown",
    "Market Expansion",
    "Market Research",
    "Marketing Automation",
    "Marketing Funnel",
    "Marketing Funnel Analysis",
    "Marketing Graphics",
    "Marketing Operations",
    "Material Design",
    "Mathematical Optimization",
    "Matplotlib",
    "Maven",
    "Memory Management",
    "Memory Safety",
    "Message Brokers",
    "Metadata Management",
    "Metadata Management setups",
    "Metamask Integration",
    "Metasploit",
    "Metrics dashboard tracking",
    "Metro Bundler",
    "Micro-Frontends",
    "Microcontrollers",
    "Microcontrollers (STM32)",
    "Microprocessors",
    "Microservices",
    "Microservices Architecture",
    "Microservices Design",
    "Milestone tracking",
    "Miter Att&ck framework",
    "Mixpanel/Amplitude Analytics",
    "Mobile App Testing (iOS/Android)",
    "Mobile Game Optimization",
    "Mobile testing",
    "Mocking API dependencies",
    "Mockito",
    "Mockups",
    "Model Deployment",
    "Model Evaluation",
    "Model Evaluation Metrics",
    "Model Monitoring",
    "Model Optimization",
    "Model ROI Analysis",
    "Model Registry",
    "Model Versioning",
    "MongoDB",
    "Mongoose",
    "Monitoring (Prometheus/Grafana)",
    "MonoBehaviour",
    "Monorepos",
    "Monorepos (Turbo/Lerna)",
    "Month-End Close",
    "Multi-Factor Authentication (MFA)",
    "Multi-Project Coordination",
    "Multi-cloud Strategy",
    "Multi-threading",
    "MySQL",
    "MySQL database backend",
    "Mythril",
    "NIST Framework",
    "NIST SP 800-61",
    "NLP Research",
    "NLTK",
    "NUnit",
    "Nagios",
    "Named Entity Recognition (NER)",
    "Native Modules",
    "Navigation Systems",
    "Negotiating Contracts",
    "Negotiation",
    "Neo4j",
    "NestJS",
    "Net Promoter Score (NPS)",
    "Network Access Control (NAC)",
    "Network Assessment",
    "Network Security",
    "Network Security Architecture",
    "Network Security groups configuration",
    "Network Services (DNS/DHCP)",
    "Network Troubleshooting",
    "Neural Architecture Search",
    "New Relic",
    "Newman CLI",
    "Next.js",
    "Next.js App Router",
    "Next.js Middleware",
    "Nginx",
    "Niagara VFX Particle systems",
    "Nmap",
    "NoSQL",
    "NoSQL Architecture",
    "NoSQL Databases",
    "Node-RED",
    "Node.js",
    "NumPy",
    "Nuxt.js",
    "OAuth",
    "OAuth 2.0",
    "OAuth2/OIDC",
    "OIDC",
    "OLAP Cubes",
    "OOPs",
    "OWASP Top 10",
    "OWASP Top 10 mitigation",
    "Object Detection",
    "Object Tracking",
    "Object-Oriented Programming",
    "Objective-C",
    "Off-Page SEO",
    "Okta",
    "On-Page SEO Optimization",
    "Onboarding",
    "Onboarding & Offboarding",
    "OpenCV",
    "Operational Efficiency",
    "Operations Management",
    "Optimization tools",
    "Oracle DB",
    "Organizational Agility",
    "Oscilloscope Debugging",
    "Oscilloscopes",
    "Ownership Model",
    "PCB Design",
    "PCI-DSS",
    "PHP",
    "PHP programming",
    "PHPUnit",
    "PIL",
    "PKI",
    "PL/SQL",
    "PPC Campaigns",
    "PRD Writing",
    "Pandas",
    "Path Planning",
    "Pattern Matching",
    "Payment Gateway integration",
    "Payroll Processing",
    "Penetration Testing",
    "Penetration Testing application layer",
    "Performance Appraisals",
    "Performance Management",
    "Performance Profiling",
    "Performance Profiling Tools",
    "Performance Reviews",
    "Performance Testing (JMeter)",
    "Performance Testing Methodology",
    "Performance Tuning",
    "Persona Creation templates",
    "Persuasive Writing",
    "Phalcon",
    "Pinecone",
    "Ping Identity",
    "Pipenv",
    "Pivot Tables",
    "Playwright",
    "Policy Drafting",
    "Policy Implementation",
    "Post-Mortem Documentation",
    "PostgreSQL",
    "Postman",
    "Postman automation collections",
    "Power BI",
    "PowerShell",
    "Print Media Design",
    "Print Production",
    "Printer & Network setup",
    "Prisma",
    "Privacy by Design",
    "Privileged Access Management (PAM)",
    "Problem Solving",
    "Process Mapping",
    "Process Optimization",
    "Product Adoption coaching",
    "Product Analytics",
    "Product Backlog Refinement",
    "Product Demos",
    "Product Design Lifecycle",
    "Product Inventory Management",
    "Product Lifecycle Management",
    "Product Marketing",
    "Product Positioning",
    "Product Roadmap",
    "Product Roadmap alignment",
    "Product Strategy",
    "Product engineering roadmaps",
    "Program Charters",
    "Program Increment (PI) Planning",
    "Program Management",
    "Project Delivery",
    "Project Management",
    "Project Planning",
    "Project Planning & Milestones",
    "Prometheus",
    "Promises",
    "Prompt Engineering",
    "Prompt Injection Mitigation",
    "Proof of Concept (PoC)",
    "Protobuf",
    "Prototyping",
    "Provider",
    "Pub.dev",
    "PyTest",
    "PyTorch",
    "Python",
    "QBR (Quarterly Business Reviews)",
    "QlikView",
    "Qt Creator",
    "Quality Assurance",
    "Query Execution Plans",
    "Query Optimization",
    "QuickBooks",
    "R",
    "R&D Innovation initiatives",
    "R&D innovation",
    "REST API",
    "REST APIs",
    "RESTful API",
    "RESTful API Design",
    "RESTful API testing",
    "RFP Responses",
    "ROI Analytics",
    "ROI Tracking",
    "ROS (Robot Operating System)",
    "RSpec",
    "RTOS",
    "RTOS (FreeRTOS)",
    "Raspberry Pi",
    "Rate Limiting & Throttling",
    "Razor Pages",
    "React",
    "React Native",
    "React Native CLI",
    "React Navigation",
    "Real Device Cloud testing (BrowserStack)",
    "Recruiting Strategy",
    "Recurrent Neural Networks (RNN)",
    "Red Teaming",
    "Redis",
    "Redshift",
    "Redux",
    "Reentrancy Attacks mitigation",
    "Regex",
    "Regression Testing",
    "Reinforcement Learning",
    "Relationship Building",
    "Release Governance",
    "Release Management",
    "Release Management governance",
    "Release Notes",
    "Remote Assistance Tools",
    "Remote Desktop Tools",
    "Remote desktop support",
    "Removing Impediments",
    "Replication",
    "Reporting",
    "Reporting Services",
    "Requirement Analysis",
    "Requirements Gathering",
    "Requirements Management Tools (DOORS)",
    "Resolving program impediments",
    "Resource Allocation",
    "Resource Management",
    "Resource Planning",
    "Resource Scheduling & Allocation",
    "Resource planning & hiring",
    "Responsive Design",
    "Responsive Layouts",
    "Responsive Web Design",
    "Responsive web pages",
    "RestAssured java framework",
    "Retention Metrics Analysis",
    "Retrofit",
    "Risk Assessment",
    "Risk Assessment & Mitigation",
    "Risk Management",
    "Risk Management & Planning",
    "Risk Management Framework (RMF)",
    "Risk Mitigation",
    "Roadmap planning",
    "Robotic Arm Control",
    "Rocket",
    "Role-Based Access Control (RBAC)",
    "Room Database",
    "Root Cause Analysis",
    "Root Cause Analysis (RCA)",
    "Ruby",
    "Ruby on Rails",
    "Rust",
    "RxJS",
    "RxJava",
    "SAFe Agile Framework scaling",
    "SAML",
    "SAP ABAP Programming",
    "SAP Configuration",
    "SAP ERP system modules",
    "SAP Fiori custom apps",
    "SAP HANA Implementation",
    "SAP NetWeaver",
    "SASS",
    "SAST/DAST Tooling",
    "SEMrush/Ahrefs",
    "SEO Copywriting",
    "SEO Optimization",
    "SEO Strategy",
    "SEO/SEM",
    "SEO/SEM Strategy",
    "SIEM",
    "SIEM (Splunk/QRadar)",
    "SIEM Tools",
    "SIEM Triaging",
    "SLA Compliance",
    "SLA Management",
    "SLA Monitoring",
    "SLAM",
    "SOAR",
    "SOAR Platforms",
    "SOC 2 Type II",
    "SOC Auditing",
    "SOC Operations",
    "SOQL/SOSL",
    "SOX Compliance",
    "SPI/I2C/UART/CAN",
    "SQL",
    "SQL Queries",
    "SQL Server",
    "SQL Server Integration Services (SSIS)",
    "SQL query optimization",
    "SQL query running",
    "SQL verification",
    "SQLAlchemy",
    "SSAS",
    "SSIS",
    "SSR & SSG",
    "SSRS",
    "STL",
    "SWR / React Query",
    "SaaS Architecture",
    "Sagemaker",
    "SailPoint",
    "Sales Cycle management",
    "Sales Enablement",
    "Sales Pitch presentation",
    "Salesforce Admin certified",
    "Salesforce Apex",
    "Salesforce Configuration",
    "Salesforce Integrations",
    "Scala",
    "Scalability",
    "Scalability & Performance design",
    "Scaling Agile (SAFe/LeSS)",
    "Schema Registry",
    "Scientific Computing",
    "Scikit-Learn",
    "Scikit-image",
    "Scope Definition",
    "Scrapy",
    "Scribble",
    "Scripting (Bash/PowerShell)",
    "Scrum",
    "Scrum & Kanban Coaching",
    "Scrum Framework",
    "Seaborn",
    "Search Schema",
    "Secure Access Service Edge (SASE)",
    "Secure Coding Guidelines coaching",
    "Security Analyst Mentoring",
    "Security Architecture",
    "Security Auditing",
    "Security Audits coordination",
    "Security Awareness training",
    "Security Controls",
    "Security Operations Center (SOC)",
    "Security Patching",
    "Security Patterns",
    "Security Vulnerability Scanning",
    "Selenium",
    "Selenium WebDriver/Playwright",
    "Semantic Search",
    "Sensor Fusion",
    "Sensor Integration",
    "Sentiment Analysis",
    "Seq2Seq",
    "Sequelize",
    "Serde",
    "Server Performance Metrics analysis",
    "Server-Side Rendering (SSR)",
    "Serverless",
    "Serverless Framework",
    "Service Blueprint mapping",
    "Service Level Agreement (SLA) monitoring",
    "Service Mesh (Istio)",
    "Service Prototyping tests",
    "Shader Development",
    "Sharding",
    "Shopify API Integration",
    "Shopify Admin API",
    "Shopify App Custom development",
    "Shopify Liquid template engine",
    "Shopify/WooCommerce Management",
    "Sidekiq",
    "SignalR",
    "Simulation (Gazebo)",
    "Single File Components (SFC)",
    "Single Sign-On (SSO)",
    "Site Mapping",
    "Sketch",
    "Smart Contract Auditing",
    "Smart Contracts",
    "Smoke Testing",
    "Snowflake",
    "Snowflake/Redshift Cloud databases",
    "Snyk",
    "SoapUI enterprise setups",
    "Social Ads Management",
    "Social Media Analytics",
    "Social Media Content",
    "Social Media Marketing",
    "Social Media Platforms",
    "Software Architecture Design",
    "Software Architecture Guidance",
    "Software Development Life Cycle (SDLC)",
    "Solidity",
    "Solution Design",
    "SonarQube",
    "SpaCy",
    "Spark",
    "Spark Streaming",
    "Spring Boot",
    "Spring Cloud",
    "Sprint Acceptance Criteria",
    "Sprint Execution",
    "Sprint Planning",
    "Sprint Planning & Management",
    "Sprint Retrospectives",
    "Sprint Review presentations",
    "Sqoop",
    "Stackdriver",
    "Stakeholder Communication",
    "Stakeholder Interviews",
    "Stakeholder Management",
    "Stakeholder Reporting",
    "Stakeholder interviews",
    "Star & Snowflake Schema design",
    "State Management",
    "State Management Patterns",
    "Static Analysis (Slither)",
    "Static Code Analysis (SAST)",
    "Static Site Generation (SSG)",
    "Statistical Analysis",
    "Statsmodels",
    "Stored Procedures",
    "Strategic Partnerships",
    "Strategic Roadmapping",
    "Strict Typing",
    "Subnetting",
    "Supply Chain Management",
    "Survey Design & analysis",
    "Swift",
    "Swift Package Manager",
    "SwiftUI",
    "Symfony",
    "SysML/UML",
    "System Architecture",
    "System Bottlenecks identification",
    "System Design",
    "System Design patterns",
    "System Modeling",
    "System Monitoring",
    "System Performance Analysis",
    "System Prompts",
    "System Requirements Gathering",
    "System Scalability",
    "System Specifications",
    "System Testing",
    "Systems Engineering",
    "Systems Integration",
    "T-SQL",
    "TCP/IP Network Protocol",
    "TFX",
    "TOGAF",
    "TSLint",
    "TSO/ISPF",
    "Tableau",
    "Tailwind CSS",
    "Talent Management",
    "Talent Pipeline",
    "Tax Compliance",
    "Tax Filing",
    "Taxonomy Design",
    "Team Building workshops",
    "Tech Editing",
    "Tech Stack Selection",
    "Tech Stack evaluation",
    "Technical Account Management",
    "Technical Architecture reviews",
    "Technical Consultation",
    "Technical Customer Support",
    "Technical Debt management",
    "Technical Documentation",
    "Technical Escalations",
    "Technical Leadership",
    "Technical Leadership & Guidance",
    "Technical Presentations",
    "Technical SEO Audit",
    "Technical Sales support",
    "Technical Specifications drafting",
    "Technical Strategy Guidance",
    "Technical Team Leadership",
    "Technical Vision",
    "Technical Writing",
    "Technology Stack evaluation",
    "Technology Strategy Planning",
    "TensorFlow",
    "TensorRT",
    "Terraform",
    "Test Automation Frameworks",
    "Test Cases",
    "Test Plans",
    "TestFlight",
    "TestNG",
    "Testing Validation methodologies",
    "Text Classification",
    "Theme customization & setups",
    "Threat Containment",
    "Threat Hunting",
    "Threat Intel Integration",
    "Threat Modeling designs",
    "Ticketing System (Zendesk/Jira)",
    "Ticketing System Management",
    "Time Management",
    "Tokenization",
    "Tokenomics",
    "Tokio",
    "Touchpoint Analysis reviews",
    "Transformers",
    "Treasury Operations",
    "Triggers",
    "Troubleshooting",
    "Truffle/Hardhat",
    "Ts-node",
    "TypeORM",
    "TypeScript",
    "Typography",
    "UART/SPI/I2C",
    "UI Canvas setup",
    "UI/UX Best practices",
    "UIKit",
    "UML Modeling",
    "UX Design",
    "UX Guidelines",
    "UX Insights Reporting",
    "Unit Testing",
    "Unit Testing (Hardhat)",
    "Unit Testing (Mocha/Chai)",
    "Unity Animation",
    "Unity Asset Store integration",
    "Unity Engine",
    "Unity Prefabs",
    "Unreal Engine",
    "Unreal Engine Editor",
    "Unreal Materials Editor",
    "Upselling",
    "Usability Testing",
    "Usability Testing protocols",
    "Use Case Documentation",
    "User Acceptance Testing (UAT)",
    "User Access administration",
    "User Acquisition strategies",
    "User Empathy Mapping",
    "User Experience Research",
    "User Flows",
    "User Guides",
    "User Interaction Flow",
    "User Interface Design",
    "User Interviews conducting",
    "User Journeys",
    "User Management",
    "User Personas",
    "User Research",
    "User Research Methods",
    "User Stories",
    "User Story Mapping",
    "User Story writing",
    "VLAN",
    "VPN Setup",
    "VPN setup & tunnels",
    "VSAM",
    "Valgrind",
    "Valuation Techniques",
    "Value Proposition",
    "Value Stream Mapping",
    "Variance Analysis",
    "Vector Art",
    "Vector Databases",
    "Vector Illustration",
    "Velocity & Throughput metrics",
    "Velocity Tracking",
    "Vendor Management",
    "Vercel",
    "Verification & Validation",
    "Views",
    "Virtualization",
    "Virtualization (VMware/Hyper-V)",
    "Visual Design",
    "Visual Hierarchy",
    "Visual Layouts",
    "Visual Mockups",
    "Visual Storytelling",
    "Visual Studio",
    "Visual Style Guides",
    "Visual Styling",
    "Visualforce",
    "Vite",
    "Vue CLI",
    "Vue Router",
    "Vue Test Utils",
    "Vue.js",
    "Vuetify / Tailwind CSS",
    "Vuex / Pinia",
    "Vulnerability Assessment & scanning",
    "Vulnerability Management",
    "Vulnerability Scanning",
    "Vulnerability management",
    "WP-CLI",
    "WPF",
    "Web API",
    "Web Application Security",
    "Web Layout Design",
    "Web Performance Optimization",
    "Web Systems Programming",
    "Web Vitals",
    "Web3",
    "Web3 UI frameworks",
    "Web3.js",
    "Web3.js/Ether.js",
    "WebAssembly",
    "WebSockets",
    "Webhooks management",
    "Webpack",
    "Webpack / Vite",
    "Webpack Module Federation",
    "Webpacker",
    "Website Speed optimization",
    "Weights & Biases",
    "Wi-Fi Configuration",
    "Wi-Fi/Bluetooth LE",
    "Widget Trees",
    "Windows Server",
    "Windows/macOS troubleshooting",
    "Wireframing",
    "Wireless Hacking",
    "Wireshark",
    "WooCommerce setups",
    "Word Embeddings",
    "WordPress",
    "WordPress Plugin development",
    "WordPress Theme customization",
    "WordPress custom styling",
    "XGBoost",
    "XML Sitemaps",
    "XUnit",
    "Xcode",
    "Xcode & Android Studio emulators",
    "Xdebug",
    "YAML",
    "YOLO",
    "Yarn",
    "Yii",
    "Zendesk",
    "Zero-Shot Learning",
    "Zustand",
    "dApps",
    "gRPC",
    "gRPC / Protobuf",
    "iOS Deployment",
    "npm",
    "tsconfig"
  ];

  /* ================= LANGUAGES ================= */
  export const ALL_LANGUAGES = ['English', 'Telugu', 'Hindi', 'Tamil', 'Kannada', 'Malayalam'];

export const SECTIONS = [
    { id: 'summary', label: 'Profile Summary' },
    { id: 'skills', label: 'Key Skills' },
    { id: 'employment', label: 'Employment History' },
    { id: 'projects', label: 'Projects' },
    { id: 'education', label: 'Education' },
    { id: 'personal', label: 'Personal Details' },
    { id: 'certifications', label: 'Certifications' },
    { id: 'achievements', label: 'Achievements & Awards' },
    { id: 'publications', label: 'Publications' },
    { id: 'customSections', label: 'Custom Sections' }
  ];

export const AVAILABLE_ROLES = [
    "AI Product Manager",
    "AI Research Scientist",
    "API Platform Engineer",
    "API Test Engineer",
    "AWS Engineer",
    "Accountant",
    "Agile Coach",
    "Android Developer",
    "Application Security Specialist",
    "Automation Test Engineer",
    "Azure Engineer",
    "Backend Architect",
    "Backend Developer",
    "Big Data Engineer",
    "Blockchain Developer",
    "Brand Designer",
    "Business Analyst",
    "Business Development Manager",
    "Business Intelligence (BI) Analyst",
    "Business Intelligence Developer",
    "C# Developer",
    "C++ Developer",
    "Chief Information Officer (CIO)",
    "Chief Technology Officer (CTO)",
    "Cloud Architect",
    "Cloud Security Engineer",
    "Computer Vision Engineer",
    "Content Strategist",
    "Copywriter",
    "Customer Success Manager",
    "Customer Support Engineer",
    "Cybersecurity Analyst",
    "Data Analyst",
    "Data Architect",
    "Data Engineer",
    "Data Governance Analyst",
    "Data Protection Officer (DPO)",
    "Data Scientist",
    "Data Warehouse Developer",
    "Database Administrator (DBA)",
    "Deep Learning Engineer",
    "Delivery Manager",
    "DevOps Engineer",
    "DevSecOps Engineer",
    "Digital Marketing Manager",
    "E-commerce Manager",
    "ETL Developer",
    "Embedded Software Engineer",
    "Embedded Systems Engineer",
    "Engineering Manager",
    "Enterprise Architect",
    "Financial Analyst",
    "Financial Controller",
    "Firmware Engineer",
    "Flutter Developer",
    "Frontend Architect",
    "Frontend Developer",
    "Full Stack Developer",
    "Full Stack QA Engineer",
    "Game Developer",
    "Go Developer",
    "Google Cloud Engineer",
    "Governance, Risk, and Compliance (GRC) Officer",
    "Graphic Designer",
    "Growth Product Manager",
    "HR Generalist",
    "HR Specialist",
    "Helpdesk Administrator",
    "IT Project Manager",
    "IT Support Technician",
    "Identity and Access Management (IAM) Specialist",
    "Incident Response Manager",
    "Information Architect",
    "Information Security Manager",
    "IoT Specialist",
    "Java Developer",
    "JavaScript Developer",
    "MLOps Engineer",
    "Machine Learning Engineer",
    "Mainframe Developer",
    "Marketing Operations Specialist",
    "Mobile QA Engineer",
    "NLP Engineer",
    "Network Engineer",
    "Network Security Engineer",
    "Next.js Developer",
    "NoSQL Specialist",
    "Operations Manager",
    "PHP Developer",
    "Penetration Tester",
    "Performance Test Engineer",
    "Principal Engineer",
    "Product Designer",
    "Product Manager",
    "Product Marketing Manager",
    "Program Manager",
    "Project Manager",
    "Prompt Engineer",
    "Python Developer",
    "QA Engineer",
    "React Native Developer",
    "Release Train Engineer",
    "Robotics Engineer",
    "Ruby on Rails Developer",
    "Rust Developer",
    "SAP Consultant",
    "SEO Specialist",
    "SQL Developer",
    "Sales Engineer",
    "Salesforce Developer",
    "Scrum Master",
    "Scrum Product Owner",
    "Security Engineer",
    "Security Operations Center (SOC) Lead",
    "Service Designer",
    "Shopify Developer",
    "Site Reliability Engineer (SRE)",
    "Smart Contract Auditor",
    "Social Media Specialist",
    "Software Architect",
    "Solidity Developer",
    "Solutions Architect",
    "Systems Administrator",
    "Systems Analyst",
    "Systems Engineer",
    "Talent Acquisition Manager",
    "Technical Account Manager",
    "Technical Lead",
    "Technical Writer",
    "TypeScript Developer",
    "UI Designer",
    "UX Designer",
    "UX Researcher",
    "Unity Developer",
    "Unreal Engine Developer",
    "Vue.js Developer",
    "Web Designer",
    "Web3 Developer",
    "WordPress Developer",
    "iOS Developer"
  ];

export const ROLE_KEYWORDS: { [key: string]: string[] } = {
    "Frontend Developer": [
      "Angular",
      "React",
      "Vue.js",
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "Redux",
      "Webpack",
      "Tailwind CSS",
      "SASS",
      "Responsive Design",
      "Flexbox",
      "Grid Layout",
      "API Integration",
      "Vite",
      "Babel",
      "npm",
      "Yarn",
      "ESLint"
    ],
    "Backend Developer": [
      "Node.js",
      "Express.js",
      "Python",
      "Django",
      "Java",
      "Spring Boot",
      "PostgreSQL",
      "MongoDB",
      "RESTful API",
      "GraphQL",
      "Redis",
      "Docker",
      "Microservices",
      "OAuth",
      "SQL",
      "gRPC",
      "Prisma",
      "Sequelize",
      "Mongoose",
      "Elasticsearch"
    ],
    "Full Stack Developer": [
      "React",
      "Angular",
      "Node.js",
      "Express.js",
      "Java",
      "Spring Boot",
      "PostgreSQL",
      "MongoDB",
      "TypeScript",
      "REST API",
      "Git",
      "Docker",
      "AWS",
      "CI/CD",
      "GraphQL",
      "Redis",
      "Next.js",
      "Vue.js",
      "Tailwind CSS",
      "System Design"
    ],
    "Java Developer": [
      "Java",
      "Spring Boot",
      "Spring Cloud",
      "Hibernate",
      "Microservices",
      "REST API",
      "SQL",
      "JUnit",
      "Maven",
      "Gradle",
      "Jenkins",
      "Git",
      "Docker",
      "AWS",
      "Design Patterns",
      "JPA",
      "JDBC",
      "Kafka",
      "WebSockets",
      "Oracle DB"
    ],
    "Python Developer": [
      "Python",
      "Django",
      "Flask",
      "FastAPI",
      "Pandas",
      "NumPy",
      "SQLAlchemy",
      "PostgreSQL",
      "REST API",
      "Docker",
      "Git",
      "Celery",
      "Redis",
      "PyTest",
      "Scrapy",
      "BeautifulSoup",
      "Asyncio",
      "Jupyter",
      "SQL",
      "Pipenv"
    ],
    "JavaScript Developer": [
      "JavaScript",
      "ES6+",
      "Node.js",
      "React",
      "Vue.js",
      "Express.js",
      "MongoDB",
      "Async/Await",
      "Promises",
      "Webpack",
      "Babel",
      "npm",
      "Jest",
      "REST API",
      "WebSockets",
      "AJAX",
      "JSON",
      "DOM Manipulation",
      "Lodash",
      "Axios"
    ],
    "TypeScript Developer": [
      "TypeScript",
      "Angular",
      "React",
      "Node.js",
      "NestJS",
      "ESNext",
      "Generics",
      "Interfaces",
      "Decorators",
      "Strict Typing",
      "TSLint",
      "Webpack",
      "Jest",
      "REST API",
      "Monorepos",
      "RxJS",
      "TypeORM",
      "Ts-node",
      "tsconfig"
    ],
    "C++ Developer": [
      "C++",
      "STL",
      "Boost",
      "CMake",
      "Multi-threading",
      "Memory Management",
      "Object-Oriented Programming",
      "Design Patterns",
      "Data Structures",
      "Algorithms",
      "GDB",
      "Valgrind",
      "Git",
      "Embedded Systems",
      "Qt Creator",
      "Concurrency",
      "Clang",
      "Visual Studio"
    ],
    "C# Developer": [
      "C#",
      ".NET Core",
      "ASP.NET MVC",
      "Entity Framework",
      "SQL Server",
      "Web API",
      "LINQ",
      "WPF",
      "Azure",
      "Microservices",
      "Docker",
      "NUnit",
      "Git",
      "Agile",
      "IIS",
      "Razor Pages",
      "SignalR",
      "Blazor",
      "XUnit"
    ],
    "PHP Developer": [
      "PHP",
      "Laravel",
      "Symfony",
      "MySQL",
      "Composer",
      "PHPUnit",
      "JavaScript",
      "HTML5",
      "CSS3",
      "REST API",
      "WordPress",
      "Docker",
      "Git",
      "Apache",
      "Nginx",
      "Yii",
      "CodeIgniter",
      "Xdebug",
      "Doctrine",
      "Phalcon"
    ],
    "Ruby on Rails Developer": [
      "Ruby",
      "Ruby on Rails",
      "PostgreSQL",
      "RSpec",
      "Sidekiq",
      "Redis",
      "Capistrano",
      "Git",
      "Docker",
      "HTML5",
      "CSS3",
      "JavaScript",
      "REST API",
      "MVC Architecture",
      "ActiveRecord",
      "Webpacker",
      "Bundler",
      "Heroku"
    ],
    "Go Developer": [
      "Go (Golang)",
      "Goroutines",
      "Channels",
      "Docker",
      "Kubernetes",
      "gRPC",
      "Microservices",
      "PostgreSQL",
      "Redis",
      "Git",
      "REST API",
      "CI/CD",
      "AWS",
      "Unit Testing",
      "Go modules",
      "Echo",
      "Gin",
      "Protobuf",
      "Concurrency"
    ],
    "Rust Developer": [
      "Rust",
      "Cargo",
      "Ownership Model",
      "Async Rust",
      "WebAssembly",
      "Tokio",
      "Concurrency",
      "Web Systems Programming",
      "Git",
      "CI/CD",
      "Docker",
      "Memory Safety",
      "Actix-web",
      "Rocket",
      "Serde",
      "Pattern Matching"
    ],
    "iOS Developer": [
      "Swift",
      "Objective-C",
      "Xcode",
      "UIKit",
      "SwiftUI",
      "Core Data",
      "CocoaPods",
      "Swift Package Manager",
      "Git",
      "App Store Connect",
      "Combine Framework",
      "REST API",
      "MVC/MVVM",
      "TestFlight",
      "Cocoa Touch",
      "Core Animation"
    ],
    "Android Developer": [
      "Kotlin",
      "Java",
      "Android Studio",
      "Jetpack Compose",
      "Retrofit",
      "Coroutines",
      "Room Database",
      "Dagger Hilt",
      "Git",
      "Google Play Console",
      "REST API",
      "MVVM Architecture",
      "Android SDK",
      "RxJava",
      "Mockito",
      "Gradle"
    ],
    "React Native Developer": [
      "React Native",
      "JavaScript",
      "TypeScript",
      "React Navigation",
      "Redux",
      "iOS Deployment",
      "Android Deployment",
      "Expo",
      "Native Modules",
      "Git",
      "REST API",
      "npm",
      "Fastlane",
      "Metro Bundler",
      "React Native CLI"
    ],
    "Flutter Developer": [
      "Dart",
      "Flutter",
      "Provider",
      "Bloc State Management",
      "Widget Trees",
      "iOS Deployment",
      "Android Deployment",
      "Git",
      "REST API",
      "Firebase Integration",
      "Material Design",
      "Cupertino Widgets",
      "Flutter CLI",
      "Pub.dev"
    ],
    "DevOps Engineer": [
      "Git",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "AWS",
      "Terraform",
      "Ansible",
      "CI/CD Pipelines",
      "Linux",
      "Python",
      "Bash Scripting",
      "Monitoring (Prometheus/Grafana)",
      "Azure",
      "YAML",
      "GitLab CI",
      "GitHub Actions",
      "Helm",
      "CloudFormation"
    ],
    "Site Reliability Engineer (SRE)": [
      "Kubernetes",
      "Docker",
      "AWS",
      "Linux",
      "Python",
      "Go",
      "Terraform",
      "CI/CD",
      "Prometheus",
      "Grafana",
      "ELK Stack",
      "System Architecture",
      "Incident Management",
      "Automation",
      "Nagios",
      "Chaos Engineering",
      "New Relic"
    ],
    "Cloud Architect": [
      "Cloud Migration",
      "Multi-cloud Strategy",
      "AWS",
      "Azure",
      "GCP",
      "Infrastructure as Code",
      "Terraform",
      "Cloud Security",
      "Enterprise Integration",
      "Cost Optimization",
      "Serverless",
      "SaaS Architecture",
      "Disaster Recovery Planning"
    ],
    "AWS Engineer": [
      "AWS",
      "Amazon EC2",
      "Amazon S3",
      "AWS Lambda",
      "Amazon RDS",
      "AWS IAM",
      "CloudFormation",
      "Terraform",
      "AWS ECS",
      "Amazon VPC",
      "CloudWatch",
      "Serverless Framework",
      "AWS Route53",
      "AWS DynamoDB",
      "AWS EKS"
    ],
    "Azure Engineer": [
      "Azure",
      "Azure Virtual Machines",
      "Azure App Services",
      "Azure SQL",
      "Azure Active Directory",
      "ARM Templates",
      "Terraform",
      "Azure DevOps",
      "Azure Kubernetes Service",
      "PowerShell",
      "Azure Functions",
      "Azure Blob Storage"
    ],
    "Google Cloud Engineer": [
      "GCP",
      "Google Compute Engine",
      "Google Cloud Storage",
      "Google Kubernetes Engine",
      "BigQuery",
      "Cloud SQL",
      "GCP IAM",
      "Terraform",
      "Stackdriver",
      "Cloud Functions",
      "GCP VPC",
      "Google Cloud Run"
    ],
    "Data Scientist": [
      "Python",
      "R",
      "Pandas",
      "NumPy",
      "Scikit-Learn",
      "Matplotlib",
      "SQL",
      "Machine Learning",
      "Statistical Analysis",
      "Data Visualization",
      "Jupyter Notebooks",
      "Feature Engineering",
      "Data Cleaning",
      "Seaborn",
      "Statsmodels",
      "A/B Testing"
    ],
    "Machine Learning Engineer": [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Scikit-Learn",
      "Machine Learning",
      "Deep Learning",
      "SQL",
      "Docker",
      "AWS",
      "Model Deployment",
      "MLOps",
      "Git",
      "Keras",
      "Model Evaluation",
      "Hyperparameter Tuning",
      "XGBoost"
    ],
    "Deep Learning Engineer": [
      "PyTorch",
      "TensorFlow",
      "Keras",
      "Convolutional Neural Networks (CNN)",
      "Recurrent Neural Networks (RNN)",
      "Transformers",
      "GPU Computing (CUDA)",
      "Python",
      "C++",
      "Model Optimization",
      "TensorRT",
      "Generative Adversarial Networks (GAN)"
    ],
    "NLP Engineer": [
      "Python",
      "NLTK",
      "SpaCy",
      "Hugging Face",
      "Transformers",
      "BERT",
      "Word Embeddings",
      "Text Classification",
      "Sentiment Analysis",
      "Named Entity Recognition (NER)",
      "Regex",
      "Gensim",
      "Tokenization",
      "Seq2Seq"
    ],
    "Computer Vision Engineer": [
      "Python",
      "C++",
      "OpenCV",
      "PyTorch",
      "TensorFlow",
      "Image Segmentation",
      "Object Detection",
      "YOLO",
      "CNNs",
      "Image Processing",
      "CUDA",
      "PIL",
      "Scikit-image",
      "Object Tracking"
    ],
    "Data Engineer": [
      "Python",
      "SQL",
      "Apache Spark",
      "Hadoop",
      "ETL Pipelines",
      "Airflow",
      "BigQuery",
      "Snowflake",
      "Kafka",
      "Data Warehousing",
      "NoSQL Databases",
      "AWS",
      "Data Modeling",
      "Databricks",
      "Redshift",
      "MapReduce"
    ],
    "Data Analyst": [
      "SQL",
      "Excel",
      "Tableau",
      "Power BI",
      "Python",
      "Pandas",
      "Data Visualization",
      "Statistical Analysis",
      "Reporting",
      "Dashboards",
      "Google Analytics",
      "Data Cleaning",
      "Data Querying",
      "Pivot Tables"
    ],
    "Database Administrator (DBA)": [
      "Database Administration",
      "SQL Server",
      "Oracle DB",
      "MySQL",
      "PostgreSQL",
      "Database Tuning",
      "Backup & Recovery",
      "High Availability",
      "Replication",
      "Security Patching",
      "Index Optimization",
      "Database Mirroring"
    ],
    "SQL Developer": [
      "SQL",
      "T-SQL",
      "PL/SQL",
      "Stored Procedures",
      "Triggers",
      "Views",
      "Database Indexes",
      "Query Optimization",
      "Database Design",
      "ETL",
      "SSIS",
      "SSRS",
      "SQL Queries",
      "Query Execution Plans"
    ],
    "NoSQL Specialist": [
      "MongoDB",
      "Cassandra",
      "Redis",
      "DynamoDB",
      "NoSQL Architecture",
      "Data Modeling",
      "Scalability",
      "Sharding",
      "Replication",
      "JSON Document Databases",
      "Graph Databases",
      "Neo4j",
      "HBase",
      "CouchDB"
    ],
    "Business Intelligence (BI) Analyst": [
      "BI Tools",
      "Power BI",
      "Tableau",
      "SSAS",
      "Data Warehousing",
      "SQL",
      "Data Modeling",
      "ETL",
      "Reporting Services",
      "KPI Dashboards",
      "Data Governance",
      "Business Analytics",
      "OLAP Cubes"
    ],
    "Big Data Engineer": [
      "Hadoop",
      "Spark",
      "Hive",
      "Scala",
      "Java",
      "Python",
      "Big Data Architecture",
      "Kafka",
      "MapReduce",
      "NoSQL",
      "Cloud Data Lakes",
      "Data Ingestion",
      "Flume",
      "Sqoop",
      "Spark Streaming"
    ],
    "QA Engineer": [
      "Quality Assurance",
      "Manual Testing",
      "Regression Testing",
      "Integration Testing",
      "System Testing",
      "Bug Tracking",
      "Jira",
      "Test Cases",
      "Test Plans",
      "Agile Testing",
      "Smoke Testing",
      "User Acceptance Testing (UAT)"
    ],
    "Automation Test Engineer": [
      "Selenium",
      "Java",
      "Python",
      "TestNG",
      "JUnit",
      "Cucumber",
      "API Testing",
      "Postman",
      "CI/CD Integration",
      "Jira",
      "Git",
      "Playwright",
      "Cypress",
      "Appium",
      "Test Automation Frameworks"
    ],
    "Security Engineer": [
      "Cybersecurity",
      "Network Security",
      "Application Security",
      "Penetration Testing",
      "Vulnerability Scanning",
      "Cryptography",
      "Firewalls",
      "SIEM",
      "Incident Response",
      "Compliance (ISO/SOC2)",
      "IDS/IPS",
      "PKI"
    ],
    "Penetration Tester": [
      "Ethical Hacking",
      "Penetration Testing",
      "Metasploit",
      "Kali Linux",
      "Burp Suite",
      "OWASP Top 10",
      "Network Assessment",
      "Web Application Security",
      "Wireless Hacking",
      "Red Teaming",
      "Nmap",
      "Wireshark"
    ],
    "Cybersecurity Analyst": [
      "Security Operations Center (SOC)",
      "Incident Response",
      "Threat Hunting",
      "SIEM Tools",
      "Wireshark",
      "Firewalls",
      "Endpoint Protection",
      "Vulnerability Management",
      "Compliance Standards",
      "IDS/IPS Logging",
      "Log Analysis"
    ],
    "Embedded Systems Engineer": [
      "Embedded C",
      "C++",
      "Microcontrollers",
      "RTOS",
      "UART/SPI/I2C",
      "Hardware Debugging",
      "Oscilloscopes",
      "Firmware Development",
      "Bare-metal Programming",
      "Circuit Design",
      "ARM Cortex",
      "PCB Design"
    ],
    "Firmware Engineer": [
      "C",
      "C++",
      "Assembly Language",
      "Device Drivers",
      "Bootloaders",
      "Microprocessors",
      "RTOS",
      "Firmware Debugging",
      "Hardware Interfacing",
      "Git",
      "Bare-metal",
      "Keil MDK"
    ],
    "IoT Specialist": [
      "IoT Architecture",
      "MQTT/CoAP",
      "Raspberry Pi",
      "Arduino",
      "Node-RED",
      "Cloud Integration",
      "IoT Security",
      "Sensor Integration",
      "Embedded Systems",
      "Wi-Fi/Bluetooth LE",
      "Edge Computing",
      "IoT Protocols"
    ],
    "Robotics Engineer": [
      "ROS (Robot Operating System)",
      "Python",
      "C++",
      "Kinematics",
      "Computer Vision",
      "Control Systems",
      "Sensor Fusion",
      "Simulation (Gazebo)",
      "Robotic Arm Control",
      "LiDAR",
      "Path Planning",
      "SLAM"
    ],
    "Systems Administrator": [
      "Linux (RedHat/Ubuntu)",
      "Windows Server",
      "Active Directory",
      "Scripting (Bash/PowerShell)",
      "System Monitoring",
      "Virtualization (VMware/Hyper-V)",
      "Network Services (DNS/DHCP)",
      "Backups",
      "User Management"
    ],
    "Network Engineer": [
      "Cisco Routing & Switching",
      "TCP/IP Network Protocol",
      "Firewalls",
      "VPN Setup",
      "Network Security",
      "DNS/DHCP Configuration",
      "Subnetting",
      "Wi-Fi Configuration",
      "Network Troubleshooting",
      "VLAN",
      "BGP/OSPF"
    ],
    "UI Designer": [
      "User Interface Design",
      "Figma",
      "Sketch",
      "Adobe XD",
      "Typography",
      "Color Theory",
      "Wireframing",
      "Prototyping",
      "Design Systems",
      "Visual Hierarchy",
      "Vector Illustration",
      "Mockups",
      "Visual Layouts"
    ],
    "UX Designer": [
      "User Experience Research",
      "User Personas",
      "Information Architecture",
      "User Journeys",
      "Figma",
      "Wireframing",
      "Prototyping",
      "Usability Testing",
      "Interaction Design",
      "UX Guidelines",
      "User Empathy Mapping",
      "Card Sorting"
    ],
    "Product Designer": [
      "Product Design Lifecycle",
      "Figma",
      "Sketch",
      "User Research",
      "Wireframing",
      "Interactive Prototyping",
      "Design Systems",
      "Product Strategy",
      "Design to Development Handoff",
      "Visual Design",
      "Design Thinking"
    ],
    "Graphic Designer": [
      "Graphic Design",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe InDesign",
      "Vector Art",
      "Typography",
      "Branding",
      "Layout Design",
      "Color Matching",
      "Print Production",
      "Digital Assets",
      "Illustration"
    ],
    "Product Manager": [
      "Product Roadmap",
      "Product Lifecycle Management",
      "Agile/Scrum",
      "User Story Mapping",
      "Jira",
      "Market Research",
      "Feature Prioritization",
      "Stakeholder Communication",
      "Product Analytics",
      "A/B Testing",
      "PRD Writing",
      "Customer Interviews"
    ],
    "Project Manager": [
      "Project Planning",
      "Budget Management",
      "Risk Assessment",
      "Resource Allocation",
      "MS Project",
      "Stakeholder Communication",
      "Agile/Waterfall",
      "Scope Definition",
      "Project Delivery",
      "Gantt Charts",
      "SLA Monitoring"
    ],
    "Scrum Master": [
      "Scrum Framework",
      "Agile Principles",
      "Sprint Planning",
      "Daily Standups",
      "Sprint Retrospectives",
      "Jira",
      "Removing Impediments",
      "Coaching Teams",
      "Velocity Tracking",
      "Burndown Charts",
      "Kanban Board Setup"
    ],
    "Agile Coach": [
      "Agile Transformation",
      "Scaling Agile (SAFe/LeSS)",
      "Coaching Leadership",
      "Agile Maturity Assessment",
      "Scrum & Kanban Coaching",
      "Team Building workshops",
      "Change Management",
      "Organizational Agility"
    ],
    "Business Analyst": [
      "Requirements Gathering",
      "Process Mapping",
      "Business Process Modeling (BPMN)",
      "SQL",
      "Excel",
      "Use Case Documentation",
      "Stakeholder Interviews",
      "Gap Analysis",
      "System Specifications",
      "User Stories"
    ],
    "HR Specialist": [
      "Human Resources",
      "Employee Relations",
      "Onboarding",
      "HR Policies",
      "HRIS Software",
      "Performance Reviews",
      "Labor Laws Compliance",
      "Conflict Resolution",
      "Employee Engagement",
      "Talent Management"
    ],
    "Talent Acquisition Manager": [
      "Recruiting Strategy",
      "Applicant Tracking Systems (ATS)",
      "Candidate Sourcing",
      "Interviewing Techniques",
      "Employer Branding",
      "Negotiation",
      "Headhunting",
      "HR Metrics",
      "Job Posting",
      "Talent Pipeline"
    ],
    "Operations Manager": [
      "Operations Management",
      "Process Optimization",
      "Budget Planning",
      "Vendor Management",
      "KPI Tracking",
      "Inventory Control",
      "Supply Chain Management",
      "Resource Allocation",
      "Operational Efficiency"
    ],
    "Financial Analyst": [
      "Financial Modeling",
      "Corporate Finance",
      "Budgeting & Forecasting",
      "SQL",
      "Excel (VBA)",
      "Financial Reporting",
      "Variance Analysis",
      "Data Analytics",
      "Valuation Techniques",
      "Market Research"
    ],
    "Accountant": [
      "General Ledger Accounting",
      "Tax Compliance",
      "Financial Auditing",
      "QuickBooks",
      "Accounts Payable/Receivable",
      "Bank Reconciliation",
      "GAAP/IFRS Principles",
      "Payroll Processing",
      "Tax Filing"
    ],
    "SEO Specialist": [
      "SEO Strategy",
      "Google Analytics",
      "Google Search Console",
      "Keyword Research",
      "On-Page SEO Optimization",
      "Off-Page SEO",
      "Link Building",
      "Technical SEO Audit",
      "SEMrush/Ahrefs",
      "XML Sitemaps",
      "Local SEO"
    ],
    "Digital Marketing Manager": [
      "Digital Marketing Strategy",
      "Google Ads",
      "Social Media Marketing",
      "Email Marketing campaigns",
      "SEO/SEM",
      "Content Marketing",
      "Budget Allocation",
      "ROI Analytics",
      "PPC Campaigns",
      "Marketing Funnel"
    ],
    "Content Strategist": [
      "Content Strategy Development",
      "Content Calendar Management",
      "Copywriting",
      "SEO Copywriting",
      "Content Audit",
      "Brand Voice alignment",
      "Social Media Content",
      "Blogging",
      "Content Distribution"
    ],
    "Social Media Specialist": [
      "Social Media Platforms",
      "Content Creation",
      "Community Management",
      "Social Media Analytics",
      "Influencer Collaboration",
      "Social Ads Management",
      "Hashtag Strategy",
      "Visual Storytelling",
      "Brand Engagement"
    ],
    "Copywriter": [
      "Copywriting",
      "Persuasive Writing",
      "Brand Storytelling",
      "Ad Copy creation",
      "SEO Copywriting",
      "Landing Page Copy",
      "Email Campaigns",
      "Content Ideation",
      "Editor skills",
      "Creative Briefs"
    ],
    "Technical Writer": [
      "Technical Documentation",
      "API Documentation",
      "User Guides",
      "Release Notes",
      "Markdown",
      "Confluence",
      "DITA/XML",
      "Tech Editing",
      "Developer Guides",
      "Instructional Design",
      "MadCap Flare"
    ],
    "Sales Engineer": [
      "Technical Sales support",
      "Product Demos",
      "RFP Responses",
      "Solution Design",
      "Technical Consultation",
      "Client Relations",
      "Proof of Concept (PoC)",
      "Sales Cycle management",
      "Technical Presentations"
    ],
    "Customer Success Manager": [
      "Customer Retention",
      "Client Onboarding",
      "Account Management",
      "Customer Satisfaction (CSAT)",
      "Upselling",
      "Product Adoption coaching",
      "Churn reduction",
      "Net Promoter Score (NPS)",
      "Client Relationships"
    ],
    "Business Development Manager": [
      "Lead Generation",
      "Sales Pitch presentation",
      "B2B Sales",
      "Client Acquisition",
      "Cold Outreach",
      "CRM Tools (Salesforce)",
      "Strategic Partnerships",
      "Negotiating Contracts",
      "Market Expansion"
    ],
    "Blockchain Developer": [
      "Blockchain Protocol Development",
      "Smart Contracts",
      "Cryptography",
      "Solidity",
      "Ethereum Virtual Machine (EVM)",
      "Web3.js/Ether.js",
      "Hyperledger Fabric",
      "Consensus Algorithms",
      "IPFS",
      "dApps"
    ],
    "Solidity Developer": [
      "Solidity",
      "Smart Contracts",
      "Truffle/Hardhat",
      "ERC20 & ERC721 Standards",
      "DeFi Protocols",
      "Unit Testing (Mocha/Chai)",
      "Ethereum Blockchain",
      "Gas Optimization",
      "Security Auditing",
      "Web3.js"
    ],
    "Solutions Architect": [
      "Enterprise Solutions Architecture",
      "Cloud Migration Planning",
      "System Design patterns",
      "Microservices Design",
      "AWS/Azure/GCP",
      "Security Architecture",
      "API Integration strategy",
      "Scalability",
      "High Availability"
    ],
    "Enterprise Architect": [
      "IT Strategy Planning",
      "Enterprise Architecture Frameworks (TOGAF)",
      "Business IT Alignment",
      "Application Portfolio Management",
      "Governance Frameworks",
      "Roadmap planning",
      "Enterprise Security"
    ],
    "Game Developer": [
      "Game Programming",
      "C++",
      "C#",
      "Unity Engine",
      "Unreal Engine",
      "Game Physics",
      "3D Math & Linear Algebra",
      "Shader Development",
      "Asset Pipeline integration",
      "Performance Profiling",
      "Cocos2d",
      "Game AI"
    ],
    "Unity Developer": [
      "Unity Engine",
      "C# Programming",
      "Game Physics",
      "UI Canvas setup",
      "Unity Animation",
      "Mobile Game Optimization",
      "Unity Asset Store integration",
      "Git version control",
      "MonoBehaviour",
      "Unity Prefabs"
    ],
    "Unreal Engine Developer": [
      "Unreal Engine",
      "C++ Game Programming",
      "Blueprints Visual Scripting",
      "Unreal Materials Editor",
      "Niagara VFX Particle systems",
      "Optimization tools",
      "Git/Perforce",
      "Unreal Engine Editor",
      "C++ Coding Standards"
    ],
    "Salesforce Developer": [
      "Salesforce Apex",
      "Lightning Web Components (LWC)",
      "SOQL/SOSL",
      "Salesforce Configuration",
      "Visualforce",
      "Apex Triggers",
      "Salesforce Integrations",
      "Salesforce Admin certified",
      "Aura Components"
    ],
    "SAP Consultant": [
      "SAP ERP system modules",
      "SAP ABAP Programming",
      "SAP HANA Implementation",
      "Business Process Mapping",
      "SAP Configuration",
      "SAP Fiori custom apps",
      "Integration testing",
      "SAP NetWeaver"
    ],
    "Network Security Engineer": [
      "Network Security Architecture",
      "Firewall Rules management",
      "Intrusion Detection/Prevention (IDS/IPS)",
      "VPN setup & tunnels",
      "Secure Access Service Edge (SASE)",
      "Network Access Control (NAC)",
      "Firewall Auditing"
    ],
    "Information Security Manager": [
      "Information Security Strategy",
      "Risk Assessment & Mitigation",
      "Security Audits coordination",
      "Compliance (ISO 27001, SOC2)",
      "Incident Response management",
      "Security Awareness training",
      "Risk Management Framework (RMF)"
    ],
    "IT Support Technician": [
      "IT Desktop Support",
      "Windows/macOS troubleshooting",
      "Active Directory Administration",
      "Hardware repair",
      "Printer & Network setup",
      "Ticketing System (Zendesk/Jira)",
      "Remote Desktop Tools"
    ],
    "Helpdesk Administrator": [
      "Helpdesk Team coordination",
      "Service Level Agreement (SLA) monitoring",
      "IT Asset Tracking Management",
      "User Access administration",
      "Knowledge Base creation",
      "Ticketing System Management"
    ],
    "Web Designer": [
      "Web Layout Design",
      "HTML5",
      "CSS3",
      "Responsive web pages",
      "Figma design layouts",
      "WordPress custom styling",
      "UI/UX Best practices",
      "Adobe Photoshop & Illustrator",
      "Visual Styling"
    ],
    "WordPress Developer": [
      "WordPress Theme customization",
      "WordPress Plugin development",
      "PHP programming",
      "MySQL database backend",
      "WooCommerce setups",
      "Elementor/Gutenberg custom blocks",
      "Website Speed optimization",
      "WP-CLI"
    ],
    "Shopify Developer": [
      "Shopify Liquid template engine",
      "Shopify App Custom development",
      "JavaScript programming",
      "HTML5 & CSS3 styling",
      "Shopify API Integration",
      "Theme customization & setups",
      "Shopify Admin API"
    ],
    "E-commerce Manager": [
      "E-commerce Store Operations",
      "Conversion Rate Optimization (CRO)",
      "Product Inventory Management",
      "Digital Marketing campaigns",
      "SEO/SEM Strategy",
      "Shopify/WooCommerce Management",
      "Payment Gateway integration"
    ],
    "Data Protection Officer (DPO)": [
      "Data Privacy Compliance",
      "GDPR/CCPA frameworks implementation",
      "Data Privacy Audits",
      "Data Privacy Impact Assessments (DPIA)",
      "Data Privacy Policies creation",
      "Data breach incident management",
      "Privacy by Design"
    ],
    "Chief Technology Officer (CTO)": [
      "Technology Strategy Planning",
      "Technical Team Leadership",
      "Software Architecture Guidance",
      "IT Infrastructure Management",
      "Budget Allocation & Planning",
      "R&D Innovation initiatives",
      "Tech Stack Selection"
    ],
    "Chief Information Officer (CIO)": [
      "IT Operations Governance",
      "Enterprise Architecture Planning",
      "Information Systems Security",
      "IT Budget Planning & Strategy",
      "Business Systems Implementation",
      "ITIL Framework"
    ],
    "IT Project Manager": [
      "IT Infrastructure Projects",
      "Project Planning & Milestones",
      "Resource Scheduling & Allocation",
      "Stakeholder Reporting",
      "Agile/Scrum Management",
      "Risk Management & Planning",
      "IT PMO"
    ],
    "Software Architect": [
      "Software Architecture Design",
      "System Design patterns",
      "Microservices Architecture",
      "Scalability & Performance design",
      "Technology Stack evaluation",
      "Technical Leadership & Guidance",
      "Architectural Styles",
      "Enterprise Design Patterns"
    ],
    "Principal Engineer": [
      "Technical Strategy Guidance",
      "Complex System design",
      "Core codebase architecture",
      "Engineering Best practices mentoring",
      "Product engineering roadmaps",
      "R&D innovation",
      "Technical Vision",
      "System Scalability"
    ],
    "Engineering Manager": [
      "Engineering Team Leadership",
      "Career growth Mentoring",
      "Sprint Planning & Management",
      "Technical Architecture reviews",
      "Resource planning & hiring",
      "Agile coaching",
      "1-on-1 Mentoring",
      "Performance Appraisals"
    ],
    "Scrum Product Owner": [
      "Product Backlog Refinement",
      "User Story writing",
      "Feature Prioritization",
      "Sprint Acceptance Criteria",
      "Customer Feedback loops",
      "Product Roadmap alignment",
      "Sprint Review presentations"
    ],
    "Data Warehouse Developer": [
      "Data Warehouse Architecture",
      "Star & Snowflake Schema design",
      "ETL Process development",
      "SQL Server Integration Services (SSIS)",
      "Snowflake/Redshift Cloud databases",
      "BI reporting integrations",
      "Dimensional Modeling"
    ],
    "ETL Developer": [
      "ETL pipeline development",
      "SQL query optimization",
      "Informatica PowerCenter / Talend",
      "Data Ingestion pipelines",
      "Data Cleaning & validations",
      "Apache Airflow scheduling",
      "Data Transformations"
    ],
    "Systems Analyst": [
      "System Requirements Gathering",
      "Technical Specifications drafting",
      "Business Process Mapping",
      "UML Modeling",
      "Integration Architectures design",
      "Testing Validation methodologies",
      "Systems Integration"
    ],
    "Mainframe Developer": [
      "COBOL Programming",
      "JCL Scripting",
      "DB2 Mainframe databases",
      "CICS Transaction processing",
      "Mainframe Troubleshooting",
      "IBM z/OS environment",
      "Batch Job Scheduling",
      "VSAM",
      "TSO/ISPF"
    ],
    "Full Stack QA Engineer": [
      "Manual QA methodologies",
      "Automation Test development",
      "Selenium WebDriver/Playwright",
      "API Testing (Postman/RestAssured)",
      "Performance Testing (JMeter)",
      "Mobile testing",
      "Jira/Git",
      "Cross-Browser Testing",
      "SQL verification"
    ],
    "Performance Test Engineer": [
      "Performance Testing Methodology",
      "Apache JMeter testing scripts",
      "LoadRunner enterprise tools",
      "Load, Stress & Soak testing",
      "System Bottlenecks identification",
      "Server Performance Metrics analysis",
      "Performance Profiling Tools"
    ],
    "API Test Engineer": [
      "RESTful API testing",
      "Postman automation collections",
      "SoapUI enterprise setups",
      "JSON Schema verification",
      "RestAssured java framework",
      "HTTP Response codes analysis",
      "Mocking API dependencies",
      "Newman CLI"
    ],
    "Mobile QA Engineer": [
      "Mobile App Testing (iOS/Android)",
      "Appium Mobile Automation",
      "Xcode & Android Studio emulators",
      "Crash Logs analysis",
      "Real Device Cloud testing (BrowserStack)",
      "Firebase App Distribution setup",
      "ADB command line"
    ],
    "DevSecOps Engineer": [
      "DevSecOps Pipeline implementation",
      "Static Code Analysis (SAST)",
      "Dynamic Code Analysis (DAST)",
      "Container Vulnerability scanning (Trivy)",
      "CI/CD Security controls",
      "AWS/Azure Cloud security",
      "Snyk",
      "SonarQube"
    ],
    "Cloud Security Engineer": [
      "Cloud Security Architecture",
      "AWS IAM Roles governance",
      "Cloud Compliance auditing",
      "Vulnerability Assessment & scanning",
      "Encryption Key Management (KMS)",
      "Network Security groups configuration",
      "CloudTrail auditing"
    ],
    "Data Governance Analyst": [
      "Data Quality Standards definition",
      "Metadata Management setups",
      "Data Lineage tracing",
      "Data Catalog tools management",
      "Data Compliance policies (HIPAA/GDPR)",
      "Data Access governance",
      "Collibra"
    ],
    "UX Researcher": [
      "User Research Methods",
      "Usability Testing protocols",
      "User Interviews conducting",
      "Survey Design & analysis",
      "Persona Creation templates",
      "UX Insights Reporting",
      "Figma wireframes review",
      "Heuristic Evaluation"
    ],
    "Service Designer": [
      "Service Blueprint mapping",
      "Customer Journey Mapping",
      "Touchpoint Analysis reviews",
      "Cross-functional workshops facilitation",
      "Service Prototyping tests",
      "Stakeholder interviews",
      "Blueprint diagrams"
    ],
    "Growth Product Manager": [
      "Growth Hacking Methodology",
      "A/B Testing design & execution",
      "User Acquisition strategies",
      "Activation Funnel optimization",
      "Mixpanel/Amplitude Analytics",
      "Conversion Rate Optimization (CRO)",
      "Retention Metrics Analysis"
    ],
    "Release Train Engineer": [
      "Program Increment (PI) Planning",
      "SAFe Agile Framework scaling",
      "Release Management governance",
      "Facilitating Agile events",
      "Resolving program impediments",
      "Metrics dashboard tracking",
      "Value Stream Mapping"
    ],
    "Application Security Specialist": [
      "Application Security Audits",
      "Secure Coding Guidelines coaching",
      "OWASP Top 10 mitigation",
      "Penetration Testing application layer",
      "Threat Modeling designs",
      "Vulnerability management",
      "SAST/DAST Tooling"
    ],
    "MLOps Engineer": [
      "MLOps",
      "MLflow",
      "Kubeflow",
      "DVC",
      "Feature Store",
      "Model Registry",
      "Sagemaker",
      "TFX",
      "Docker",
      "Kubernetes",
      "CI/CD for ML",
      "Model Monitoring",
      "Data Drift",
      "Prometheus",
      "Grafana",
      "Model Versioning",
      "Weights & Biases"
    ],
    "Data Architect": [
      "Data Architecture",
      "Enterprise Data Model",
      "Data Modeling",
      "ERD",
      "Data Warehouse",
      "Data Lakehouse",
      "Snowflake",
      "Databricks",
      "Redshift",
      "Data Governance",
      "Metadata Management",
      "TOGAF",
      "Dimensional Modeling",
      "Data Lineage",
      "Schema Registry"
    ],
    "Prompt Engineer": [
      "Prompt Engineering",
      "Large Language Models (LLMs)",
      "Generative AI",
      "Few-Shot Learning",
      "Zero-Shot Learning",
      "Chain-of-Thought",
      "LangChain",
      "LlamaIndex",
      "Semantic Search",
      "Prompt Injection Mitigation",
      "System Prompts",
      "AI Agents",
      "Vector Databases",
      "ChromaDB",
      "Pinecone",
      "Fine-Tuning Prompts"
    ],
    "AI Product Manager": [
      "AI Product Management",
      "Generative AI",
      "LLMs",
      "Machine Learning Lifecycle",
      "AI Ethics",
      "AI Roadmapping",
      "User Story Mapping",
      "Product Analytics",
      "Model Evaluation Metrics",
      "Dataset Curation",
      "AI Safety",
      "A/B Testing",
      "Feasibility Study",
      "Model ROI Analysis"
    ],
    "AI Research Scientist": [
      "AI Research",
      "Deep Learning",
      "Reinforcement Learning",
      "Transformers",
      "Neural Architecture Search",
      "Mathematical Optimization",
      "PyTorch",
      "TensorFlow",
      "Academic Writing",
      "JAX",
      "LaTeX",
      "Scientific Computing",
      "Algorithms Design",
      "NLP Research",
      "Convex Optimization"
    ],
    "Business Intelligence Developer": [
      "BI Development",
      "SSAS",
      "SSIS",
      "SSRS",
      "Power BI",
      "Tableau",
      "DAX",
      "MDX",
      "Data Modeling",
      "ETL Pipelines",
      "Data Warehousing",
      "SQL",
      "SQL Server",
      "Dashboard Design",
      "KPI Tracking",
      "QlikView",
      "BusinessObjects"
    ],
    "Identity and Access Management (IAM) Specialist": [
      "IAM",
      "Active Directory",
      "Azure AD",
      "Okta",
      "OAuth 2.0",
      "OIDC",
      "SAML",
      "Single Sign-On (SSO)",
      "Multi-Factor Authentication (MFA)",
      "Role-Based Access Control (RBAC)",
      "Privileged Access Management (PAM)",
      "SailPoint",
      "Ping Identity",
      "Directory Services",
      "Kerberos",
      "IAM Governance"
    ],
    "Governance, Risk, and Compliance (GRC) Officer": [
      "GRC",
      "ISO 27001",
      "SOC 2 Type II",
      "NIST Framework",
      "HIPAA Compliance",
      "PCI-DSS",
      "Risk Assessment",
      "Internal Auditing",
      "Policy Drafting",
      "Compliance Monitoring",
      "Security Controls",
      "Business Continuity Planning (BCP)",
      "Disaster Recovery (DR)",
      "SOX Compliance",
      "COBIT"
    ],
    "Incident Response Manager": [
      "Incident Response",
      "Incident Command",
      "Root Cause Analysis (RCA)",
      "Post-Mortem Documentation",
      "Threat Containment",
      "Digital Forensics",
      "SIEM Triaging",
      "Crisis Communication",
      "Disaster Recovery",
      "NIST SP 800-61",
      "SOAR Platforms",
      "Threat Intel Integration",
      "Forensic Toolkits (FTK)",
      "EnCase"
    ],
    "Security Operations Center (SOC) Lead": [
      "SOC Operations",
      "SIEM (Splunk/QRadar)",
      "SOAR",
      "Intrusion Detection",
      "Log Analysis",
      "Endpoint Detection & Response (EDR)",
      "Wireshark",
      "Threat Hunting",
      "Incident Escalation",
      "Security Analyst Mentoring",
      "KPI Metrics Reporting",
      "Vulnerability Management",
      "Miter Att&ck framework",
      "SOC Auditing"
    ],
    "Product Marketing Manager": [
      "Product Marketing",
      "Go-To-Market (GTM) Strategy",
      "Competitive Analysis",
      "Buyer Personas",
      "Product Positioning",
      "Value Proposition",
      "Content Marketing",
      "Sales Enablement",
      "Market Research",
      "Launch Management",
      "Customer Case Studies",
      "Campaign Analytics",
      "Lead Generation",
      "Product Demos"
    ],
    "Brand Designer": [
      "Brand Identity Design",
      "Logo Design",
      "Visual Style Guides",
      "Typography",
      "Color Theory",
      "Adobe Illustrator",
      "Adobe Photoshop",
      "Adobe InDesign",
      "Brand Assets Creation",
      "Vector Art",
      "Design Systems",
      "Corporate Branding",
      "Print Media Design",
      "Marketing Graphics",
      "Visual Mockups",
      "Brand Strategy"
    ],
    "Information Architect": [
      "Information Architecture",
      "Content Inventory",
      "Site Mapping",
      "Card Sorting",
      "User Flows",
      "Figma wireframes",
      "Taxonomy Design",
      "Navigation Systems",
      "UX Design",
      "Wireframing",
      "Search Schema",
      "Usability Testing",
      "Content Modeling",
      "User Interaction Flow"
    ],
    "Frontend Architect": [
      "Frontend Architecture",
      "Micro-Frontends",
      "Webpack Module Federation",
      "State Management Patterns",
      "Web Performance Optimization",
      "Design Systems",
      "TypeScript",
      "Monorepos (Turbo/Lerna)",
      "CI/CD for Frontend",
      "SSR & SSG",
      "Core Web Vitals",
      "Angular/React Core",
      "Linting & Testing Standards",
      "Browser Rendering Path",
      "CSS Architectures"
    ],
    "Backend Architect": [
      "Backend Architecture",
      "Microservices Design",
      "System Scalability",
      "Database Partitioning",
      "Caching Strategies (Redis)",
      "Event-Driven Architecture (Kafka)",
      "API Gateway design",
      "Distributed Systems",
      "Load Balancing",
      "High Availability",
      "Design Patterns",
      "gRPC / Protobuf",
      "Security Patterns",
      "Database Replication",
      "Message Brokers"
    ],
    "Web3 Developer": [
      "Web3",
      "Blockchain Protocols",
      "Smart Contracts",
      "Solidity",
      "Ethers.js",
      "Web3.js",
      "IPFS",
      "Decentralized Apps (dApps)",
      "Truffle/Hardhat",
      "Ethereum",
      "Cryptography",
      "DeFi",
      "Tokenomics",
      "Metamask Integration",
      "Web3 UI frameworks",
      "DAO Infrastructure"
    ],
    "Smart Contract Auditor": [
      "Smart Contract Auditing",
      "Solidity",
      "Security Vulnerability Scanning",
      "Static Analysis (Slither)",
      "Mythril",
      "Reentrancy Attacks mitigation",
      "Gas Optimization",
      "Formal Verification",
      "DeFi Hack analysis",
      "Audit Report Writing",
      "Unit Testing (Hardhat)",
      "Scribble",
      "Echidna fuzzing",
      "Audit Methodology"
    ],
    "Embedded Software Engineer": [
      "Embedded Software",
      "Embedded C",
      "C++",
      "RTOS (FreeRTOS)",
      "Bare-Metal Programming",
      "Device Drivers",
      "HAL (Hardware Abstraction Layer)",
      "SPI/I2C/UART/CAN",
      "Microcontrollers (STM32)",
      "Oscilloscope Debugging",
      "Assembly",
      "Git",
      "Hardware Interfacing",
      "JTAG debugging",
      "Logic Analyzers"
    ],
    "Systems Engineer": [
      "Systems Engineering",
      "System Architecture",
      "Requirement Analysis",
      "Hardware-Software Integration",
      "Verification & Validation",
      "DO-178C/ISO 26262 Compliance",
      "SysML/UML",
      "Risk Management",
      "System Modeling",
      "Technical Leadership",
      "System Performance Analysis",
      "Requirements Management Tools (DOORS)"
    ],
    "API Platform Engineer": [
      "API Platform Engineering",
      "API Gateway (Kong/Apigee)",
      "RESTful API Design",
      "GraphQL Federation",
      "gRPC",
      "OAuth2/OIDC",
      "Rate Limiting & Throttling",
      "API Documentation (OpenAPI/Swagger)",
      "API Developer Portal",
      "Microservices",
      "Service Mesh (Istio)",
      "Kong Plugins",
      "Apigee Policies",
      "Webhooks management"
    ],
    "Next.js Developer": [
      "Next.js",
      "React",
      "Server-Side Rendering (SSR)",
      "Static Site Generation (SSG)",
      "Incremental Static Regeneration (ISR)",
      "Vercel",
      "Tailwind CSS",
      "TypeScript",
      "Next.js App Router",
      "API Routes",
      "SEO Optimization",
      "Web Vitals",
      "State Management",
      "Next.js Middleware",
      "Zustand",
      "SWR / React Query"
    ],
    "Vue.js Developer": [
      "Vue.js",
      "Vuex / Pinia",
      "Vue Router",
      "Composition API",
      "Nuxt.js",
      "JavaScript",
      "TypeScript",
      "HTML5 & CSS3",
      "Vuetify / Tailwind CSS",
      "Webpack / Vite",
      "Component Design",
      "Responsive Layouts",
      "Vue CLI",
      "Vue Test Utils",
      "Single File Components (SFC)"
    ],
    "Technical Account Manager": [
      "Technical Account Management",
      "Enterprise Client Support",
      "SLA Management",
      "Technical Escalations",
      "Product Roadmap alignment",
      "Customer Success",
      "QBR (Quarterly Business Reviews)",
      "Root Cause Analysis",
      "Relationship Building",
      "Cross-functional Advocacy",
      "Client Retention",
      "Incident Reporting"
    ],
    "Delivery Manager": [
      "Delivery Management",
      "Agile Delivery",
      "Sprint Execution",
      "Project Planning",
      "Velocity & Throughput metrics",
      "Jira/Confluence",
      "Stakeholder Communication",
      "Resource Management",
      "Risk Mitigation",
      "Dependency Mapping",
      "Cross-functional Collaboration",
      "Release Governance",
      "Agile metrics tracking"
    ],
    "Program Manager": [
      "Program Management",
      "Multi-Project Coordination",
      "Strategic Roadmapping",
      "Stakeholder Management",
      "Budget Administration",
      "Risk Management",
      "Resource Planning",
      "KPI Dashboards",
      "Cross-functional Leadership",
      "Change Management",
      "Governance Frameworks",
      "Program Charters",
      "Milestone tracking"
    ],
    "Marketing Operations Specialist": [
      "Marketing Operations",
      "HubSpot / Marketo",
      "Marketing Automation",
      "Lead Scoring",
      "CRM Integration (Salesforce)",
      "Email Campaign Setup",
      "Campaign Analytics",
      "A/B Testing",
      "Data Cleansing",
      "ROI Tracking",
      "Marketing Funnel Analysis",
      "Attribution Modeling",
      "Data Privacy compliance"
    ],
    "HR Generalist": [
      "HR Generalist",
      "Employee Relations",
      "Policy Implementation",
      "Onboarding & Offboarding",
      "HRIS (Workday/BambooHR)",
      "Labor Law Compliance",
      "Performance Management",
      "Benefits Administration",
      "Conflict Resolution",
      "Employee Engagement",
      "HR Metrics",
      "FMLA compliance",
      "Employee handbook creation"
    ],
    "Financial Controller": [
      "Financial Control",
      "General Ledger",
      "Internal Controls",
      "Financial Auditing",
      "GAAP/IFRS Compliance",
      "Financial Reporting",
      "Budget Management",
      "Treasury Operations",
      "ERP Systems (SAP/Oracle)",
      "Tax Compliance",
      "Month-End Close",
      "Financial Audits coordination",
      "Balance Sheet reconciliation"
    ],
    "Customer Support Engineer": [
      "Technical Customer Support",
      "Troubleshooting",
      "Zendesk",
      "Jira Service Desk",
      "SLA Compliance",
      "SQL query running",
      "Log Analysis",
      "Bug reporting",
      "Customer Communication",
      "Knowledge Base articles",
      "Remote Assistance Tools",
      "Remote desktop support",
      "IT Service Management (ITSM)"
    ],
    "Technical Lead": [
      "Technical Leadership",
      "System Architecture",
      "Code Reviews",
      "Developer Mentoring",
      "Agile Methodologies",
      "Design Patterns",
      "Technical Debt management",
      "Tech Stack evaluation",
      "Sprint Planning",
      "Cross-functional collaboration",
      "Core codebase ownership",
      "Sprint Retrospectives",
      "Release Management"
    ]
  };

  /* ================= SECTION HELP TIPS ================= */
  export const SECTION_GUIDELINES: { [key: string]: { title: string; tips: string[] } } = {
    'summary': {
      title: 'Profile Summary Guidelines',
      tips: [
        'Keep it concise: 2 to 4 sentences highlighting your core competencies and years of learning.',
        'Use strong action verbs and mention your software architecture or frontend proficiency.',
        'Avoid generic descriptors; focus on specific technologies and project achievements.'
      ]
    },
    'skills': {
      title: 'Skills & Keywords Tips',
      tips: [
        'List 6 to 15 key technical competencies matching your target career tracks.',
        'Click industry keywords below to automatically parse and append tags to your profile.',
        'Balance languages, databases, cloud, and tools (e.g. Java, PostgreSQL, AWS, Git).'
      ]
    },
    'employment': {
      title: 'Work History Tips',
      tips: [
        'Detail your duties using bulleted lists starting with active terms ("Built", "Managed", "Implemented").',
        'Add quantitative figures if possible (e.g., "reduced latency by 25%", "improved code coverage by 15%").',
        'Reference specific technologies employed in each position description.'
      ]
    },
    'projects': {
      title: 'Project Portfolio Tips',
      tips: [
        'Highlight 1 to 3 projects showcasing practical coding and system architectures.',
        'Follow the STAR format: specify Situation, Task, Action taken, and Results achieved.',
        'Include repository links (GitHub) or sandbox references to demonstrate active code.'
      ]
    },
    'education': {
      title: 'Education Tips',
      tips: [
        'List degrees in reverse chronological order with college/university details.',
        'Add GPA or percentage details if you are a fresher or entry-level candidate.',
        'Optionally include key specializations or thesis focus.'
      ]
    },
    'personal': {
      title: 'Personal Details Tips',
      tips: [
        'Ensure professional links (LinkedIn & GitHub) are accurate and fully qualified.',
        'Select all languages in which you possess professional working proficiency.',
        'Keep date of birth and location specifications minimal.'
      ]
    }
  };

export interface ResumeTemplate {
  id: string;
  name: string;
  color: string;
  tier: string;
  photo: boolean;
  graphics: string;
  columns: number;
  baseLayout?: string;
}

export const TEMPLATES: ResumeTemplate[] = [
    { id: 'template1', name: 'Standard Classic', color: '#1e293b', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 1 },
    { id: 'template2', name: 'Corporate Modern', color: '#4f46e5', tier: 'FREE', photo: false, graphics: 'MODERNIST', columns: 1 },
    { id: 'template3', name: 'Dual Column', color: '#0ea5e9', tier: 'FREE', photo: true, graphics: 'CLEAN', columns: 2 },
    { id: 'template4', name: 'Tech Developer', color: '#10b981', tier: 'FREE', photo: false, graphics: 'MINIMALIST', columns: 1 },
    { id: 'template5', name: 'Executive Serif', color: '#9d174d', tier: 'FREE', photo: false, graphics: 'MODERNIST', columns: 1 },
    { id: 'template6', name: 'Minimalist Clean', color: '#64748b', tier: 'FREE', photo: false, graphics: 'MINIMALIST', columns: 1 },
    { id: 'template7', name: 'Bold Left Border', color: '#dc2626', tier: 'FREE', photo: false, graphics: 'CREATIVE', columns: 1 },
    { id: 'template8', name: 'Accent Top Header', color: '#7c3aed', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 1 },
    { id: 'template9', name: 'Academic CV', color: '#0369a1', tier: 'FREE', photo: false, graphics: 'MINIMALIST', columns: 1 },
    { id: 'template10', name: 'Startup Creative', color: '#db2777', tier: 'FREE', photo: false, graphics: 'CREATIVE', columns: 2 },
    { id: 'template11', name: 'Elegant Royal', color: '#d97706', tier: 'FREE', photo: false, graphics: 'MODERNIST', columns: 2 },
    { id: 'template12', name: 'Navy Compact', color: '#1e3a8a', tier: 'FREE', photo: false, graphics: 'MINIMALIST', columns: 1 },
    { id: 'template13', name: 'Teal Modern', color: '#0f766e', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 1 },
    { id: 'template14', name: 'Charcoal Corp', color: '#334155', tier: 'FREE', photo: false, graphics: 'MODERNIST', columns: 1 },
    { id: 'template15', name: 'Left Bar Minimal', color: '#475569', tier: 'FREE', photo: false, graphics: 'MINIMALIST', columns: 2 },
    { id: 'template16', name: 'Slate Standard', color: '#0284c7', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 1 },
    { id: 'template17', name: 'Orange Bold', color: '#ea580c', tier: 'FREE', photo: false, graphics: 'CREATIVE', columns: 1 },
    { id: 'template18', name: 'Clean Split', color: '#0369a1', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 2 },
    { id: 'template19', name: 'Retro Terminal', color: '#16a34a', tier: 'FREE', photo: false, graphics: 'CREATIVE', columns: 1 },
    { id: 'template20', name: 'Creative Portfolio', color: '#be185d', tier: 'FREE', photo: false, graphics: 'CREATIVE', columns: 2 },
    { id: 'template21', name: 'Luxury Gold', color: '#b59410', tier: 'PRO', photo: false, graphics: 'MODERNIST', columns: 2 },
    { id: 'template22', name: 'Executive Crimson', color: '#880808', tier: 'PRO', photo: false, graphics: 'MODERNIST', columns: 1 },
    { id: 'template23', name: 'Tech Lead Minimal', color: '#0f172a', tier: 'PRO', photo: false, graphics: 'MINIMALIST', columns: 1 },
    { id: 'template24', name: 'Startup Creative Premium', color: '#ec4899', tier: 'PRO', photo: false, graphics: 'CREATIVE', columns: 2 },
    { id: 'template25', name: 'Academic Premium', color: '#111827', tier: 'PRO', photo: false, graphics: 'MINIMALIST', columns: 1 },
    { id: 'template26', name: 'Pro Modernist', color: '#06b6d4', tier: 'PRO', photo: false, graphics: 'MODERNIST', columns: 1 },
    { id: 'template27', name: 'Pro Minimal Dark', color: '#0f172a', tier: 'PRO', photo: false, graphics: 'MINIMALIST', columns: 1 },
    { id: 'template28', name: 'Pro Executive Navy', color: '#1e3a8a', tier: 'PRO', photo: false, graphics: 'MODERNIST', columns: 1 },
    { id: 'template29', name: 'Pro Tech Showcase', color: '#10b981', tier: 'PRO', photo: false, graphics: 'CREATIVE', columns: 1 },
    { id: 'template30', name: 'Pro Creative Indigo', color: '#6366f1', tier: 'PRO', photo: false, graphics: 'CREATIVE', columns: 2 },
    { id: 'template31', name: 'Pro Split Slate', color: '#475569', tier: 'PRO', photo: false, graphics: 'CLEAN', columns: 2 },
    { id: 'template32', name: 'Pro Accent Emerald', color: '#059669', tier: 'PRO', photo: false, graphics: 'CLEAN', columns: 1 },
    { id: 'template33', name: 'Pro Bold Crimson', color: '#b91c1c', tier: 'PRO', photo: false, graphics: 'CREATIVE', columns: 1 },
    { id: 'template34', name: 'Pro Elegant Teal', color: '#0d9488', tier: 'PRO', photo: false, graphics: 'CLEAN', columns: 2 },
    { id: 'template35', name: 'Pro Classic Border', color: '#4f46e5', tier: 'PRO', photo: false, graphics: 'CLEAN', columns: 1 },
    { id: 'template36', name: 'Elite Plus Gold Premium', color: '#d97706', tier: 'ELITE', photo: false, graphics: 'CREATIVE', columns: 2 },

    // Dynamic Customizer Templates 37-50
    { id: 'template37', name: 'Elite Creative Designer', color: '#be185d', tier: 'ELITE', photo: true, graphics: 'CREATIVE', columns: 2, baseLayout: 'template36' },
    { id: 'template38', name: 'Elite Executive Corporate', color: '#1e293b', tier: 'ELITE', photo: false, graphics: 'MODERNIST', columns: 1, baseLayout: 'template22' },
    { id: 'template39', name: 'Elite Modern Minimalist', color: '#334155', tier: 'ELITE', photo: false, graphics: 'MINIMALIST', columns: 1, baseLayout: 'template27' },
    { id: 'template40', name: 'Elite Tech Startup', color: '#10b981', tier: 'ELITE', photo: true, graphics: 'CREATIVE', columns: 1, baseLayout: 'template4' },
    { id: 'template41', name: 'Pro Elegant Royal', color: '#d97706', tier: 'PRO', photo: false, graphics: 'MODERNIST', columns: 2, baseLayout: 'template34' },
    { id: 'template42', name: 'Pro Slate Split', color: '#475569', tier: 'PRO', photo: true, graphics: 'CLEAN', columns: 2, baseLayout: 'template31' },
    { id: 'template43', name: 'Pro Clean Border', color: '#7c3aed', tier: 'PRO', photo: false, graphics: 'CLEAN', columns: 1, baseLayout: 'template35' },
    { id: 'template44', name: 'Pro Creative Column', color: '#db2777', tier: 'PRO', photo: true, graphics: 'CREATIVE', columns: 2, baseLayout: 'template20' },
    { id: 'template45', name: 'Pro Tech Lead Dark', color: '#0f172a', tier: 'PRO', photo: false, graphics: 'MODERNIST', columns: 1, baseLayout: 'template23' },
    { id: 'template46', name: 'Pro Accent Top Bold', color: '#dc2626', tier: 'PRO', photo: false, graphics: 'CLEAN', columns: 1, baseLayout: 'template33' },
    { id: 'template47', name: 'Pro Startup Compact', color: '#1e3a8a', tier: 'PRO', photo: false, graphics: 'MINIMALIST', columns: 2, baseLayout: 'template15' },
    { id: 'template48', name: 'Free Classic Simple', color: '#1e293b', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 1, baseLayout: 'template1' },
    { id: 'template49', name: 'Free Corporate Basic', color: '#4f46e5', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 1, baseLayout: 'template2' },
    { id: 'template50', name: 'Free Two-Column Basic', color: '#0ea5e9', tier: 'FREE', photo: false, graphics: 'CLEAN', columns: 2, baseLayout: 'template3' }
  ];
