import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { catchError, of } from 'rxjs';

interface Chapter {
  title: string;
  duration: string;
  code: string;
  logs: string[];
}

interface FlowStep {
  step: string;
  title: string;
  desc: string;
}

interface Track {
  id: string;
  name: string;
  tag: string;
  icon: string;
  difficulty: string;
  duration: string;
  salary: string;
  chapters: Chapter[];
  flowSteps: FlowStep[];
  techStack: string[];
  shortDesc: string;
}

@Component({
  selector: 'app-explore-tracks',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './explore-tracks.html',
  styleUrls: ['./explore-tracks.css'],
})
export class ExploreTracksComponent implements OnInit, OnDestroy {
  tracks: Track[] = [
    {
      id: 'java',
      name: 'Java Full Stack Development',
      tag: 'Enterprise Backend & Web Systems',
      icon: 'fa-brands fa-java',
      difficulty: 'Intermediate',
      duration: '6 Months',
      salary: '₹4.5 - ₹16 LPA',
      shortDesc: 'Master modern enterprise computing, scalable cloud APIs, and microservices architecture.',
      techStack: ['Java 17', 'Spring Boot', 'PostgreSQL', 'Docker', 'REST API', 'Microservices'],
      chapters: [
        {
          title: 'Introduction to Java Syntax, JVM & JDK Configurations',
          duration: '12 mins',
          code: `public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, VidhuraTech students!");\n        int enrolled = 240;\n        System.out.println("Active batch count: " + enrolled);\n    }\n}`,
          logs: [
            'Executing: javac HelloWorld.java',
            'Compilation check: 0 warnings, 0 errors',
            'Executing: java HelloWorld',
            'Output: Hello, VidhuraTech students!',
            'Output: Active batch count: 240'
          ]
        },
        {
          title: 'Core OOP Principles: Classes, Interfaces & Polymorphism',
          duration: '28 mins',
          code: `interface Service { void execute(); }\n\nclass App implements Service {\n    public void execute() {\n        System.out.println("OOP Model Initialized successfully.");\n    }\n}`,
          logs: [
            'Analyzing interface mappings...',
            'Injecting dependencies into App class context',
            'Executing App.execute() invocation',
            'Output: OOP Model Initialized successfully.'
          ]
        },
        {
          title: 'Building REST API Controllers with Spring Boot Starter',
          duration: '45 mins',
          code: `@RestController\n@RequestMapping("/api/v1")\npublic class CourseController {\n    @GetMapping("/active")\n    public ResponseEntity<String> getCourses() {\n        return ResponseEntity.ok("Java, Spring Boot, microservices");\n    }\n}`,
          logs: [
            'Starting Spring application context on Tomcat port 8080',
            'Scanning annotations inside controller layer...',
            'Mapped route: GET /api/v1/active',
            'Tomcat web server online.'
          ]
        },
        {
          title: 'Data Persistence with JPA, Hibernate & PostgreSQL',
          duration: '35 mins',
          code: `@Entity\n@Table(name = "students")\npublic class Student {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    private String name;\n    private String email;\n}`,
          logs: [
            'Initializing HikariCP connection pool to Postgres DB...',
            'Hibernate: create table students (id bigint generated by default, name varchar, email varchar)',
            'Schema update complete. JPA operational.'
          ]
        },
        {
          title: 'Dockerizing the Spring Boot Backend Environment',
          duration: '22 mins',
          code: `FROM openjdk:17-alpine\nWORKDIR /app\nCOPY target/vidhura-app.jar app.jar\nEXPOSE 8080\nENTRYPOINT ["java", "-jar", "app.jar"]`,
          logs: [
            'Docker: Step 1/5 FROM openjdk:17-alpine -> Pulling metadata',
            'Docker: Copying target jar file into workspace',
            'Docker: Image tagged: vidhuratech/java-backend:latest',
            'Output: Container launched and logging active.'
          ]
        }
      ],
      flowSteps: [
        { step: '01', title: 'Live Architecture Session', desc: 'Attend mentor-led lecture on REST APIs.' },
        { step: '02', title: 'Video Playback Review', desc: 'Replay the lecture recording with code sidebars.' },
        { step: '03', title: 'Interactive Coding Labs', desc: 'Solve core Java assignments in the compile sandbox.' },
        { step: '04', title: 'Continuous Assessment', desc: 'Receive automated grading and trainer feedback.' },
        { step: '05', title: 'Mock Panel Interview', desc: 'Test skills with DevOps/Java industry professionals.' }
      ]
    },
    {
      id: 'python',
      name: 'Python Data Science & AI',
      tag: 'AI, Machine Learning & Analytics',
      icon: 'fa-brands fa-python',
      difficulty: 'Beginner Friendly',
      duration: '5 Months',
      salary: '₹4.0 - ₹15 LPA',
      shortDesc: 'Design predictive models, clean complex datasets, and integrate state-of-the-art AI APIs.',
      techStack: ['Python 3', 'Pandas & NumPy', 'Scikit-Learn', 'PyTorch', 'FastAPI', 'Jupyter'],
      chapters: [
        {
          title: 'Python Syntax Foundations, Lists, Dicts & Loops',
          duration: '15 mins',
          code: `def greet(name):\n    return f"Welcome {name} to VidhuraTech Python Track!"\n\nfor student in ["Naveen", "Anil", "Suresh"]:\n    print(greet(student))`,
          logs: [
            'Executing python script foundations.py',
            'Output: Welcome Naveen to VidhuraTech Python Track!',
            'Output: Welcome Anil to VidhuraTech Python Track!',
            'Output: Welcome Suresh to VidhuraTech Python Track!'
          ]
        },
        {
          title: 'Data Analysis and Wrangling with Pandas & NumPy DataFrames',
          duration: '32 mins',
          code: `import pandas as pd\nimport numpy as np\n\ndata = {'Track': ['Java', 'Python', 'DevOps'], 'Students': [120, 150, 180]}\ndf = pd.DataFrame(data)\nprint("Mean Enrolled:", df['Students'].mean())`,
          logs: [
            'Loading pandas framework C extension layers...',
            'DataFrame allocated memory block of size 128 bytes',
            'Output: Mean Enrolled: 150.0'
          ]
        },
        {
          title: 'Supervised Learning Models: Scikit-Learn Regressions',
          duration: '40 mins',
          code: `from sklearn.linear_model import LinearRegression\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nscore = model.score(X_test, y_test)\nprint(f"Test Accuracy Score: {score * 100:.2f}%")`,
          logs: [
            'Importing scikit-learn training modules',
            'Model fitting iterations in progress (Solver = lbfgs)',
            'Gradient calculation complete.',
            'Output: Test Accuracy Score: 94.25%'
          ]
        },
        {
          title: 'Deep Learning: Neural Networks & PyTorch Frameworks',
          duration: '50 mins',
          code: `import torch\nimport torch.nn as nn\n\nclass Net(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.fc = nn.Linear(10, 2)\n        \nmodel = Net().to("cuda")`,
          logs: [
            'Scanning available GPU hardware adapters...',
            'CUDA backend online. GPU Name: NVIDIA RTX 4080',
            'Allocated PyTorch tensor memory block.',
            'Model compiled on CUDA kernel.'
          ]
        },
        {
          title: 'Deploying Custom Models as API routes using FastAPI',
          duration: '25 mins',
          code: `from fastapi import FastAPI\napp = FastAPI()\n\n@app.get("/predict")\ndef get_predictions(features: list):\n    # Mock model return\n    return {"class": "Python Data Analyst", "confidence": 0.96}`,
          logs: [
            'Spinning up Uvicorn web server runtime',
            'API Documentation swagger endpoints established',
            'Server listening at: http://127.0.0.1:8000',
            'API logs online.'
          ]
        }
      ],
      flowSteps: [
        { step: '01', title: 'Live Data Science Class', desc: 'Analyze real datasets live with interactive charts.' },
        { step: '02', title: 'Visual Playback Sync', desc: 'Review Seaborn plotting steps and logic.' },
        { step: '03', title: 'Jupyter Challenge Lab', desc: 'Train models inside the Jupyter sandbox terminal.' },
        { step: '04', title: 'Pipeline Submissions', desc: 'Submit prediction model accuracy files.' },
        { step: '05', title: 'ML System Design Mock', desc: 'Drill mock sessions on pipeline scaling.' }
      ]
    },
    {
      id: 'devops',
      name: 'Cloud & DevOps Engineering',
      tag: 'Infrastructure, Security & Deployment Pipelines',
      icon: 'fa-solid fa-server',
      difficulty: 'Advanced',
      duration: '6 Months',
      salary: '₹5.5 - ₹20 LPA',
      shortDesc: 'Deploy high-availability containers, automate cloud infrastructure, and build CI/CD pipelines.',
      techStack: ['AWS Cloud', 'Docker Containers', 'Kubernetes Orchestration', 'Terraform IaC', 'GitHub Actions', 'Jenkins'],
      chapters: [
        {
          title: 'Linux Filesystems, Permissions, Cron Jobs & Bash scripting',
          duration: '20 mins',
          code: `#!/bin/bash\n# Disk usage checking automation script\nthreshold=80\ncurrent_usage=$(df -h / | awk 'NR==2 {print $5}' | cut -d'%' -f1)\n\nif [ $current_usage -gt $threshold ]; then\n    echo "WARNING: Disk space exceeded limit!"\nfi`,
          logs: [
            'Executing backup.sh cron script...',
            'df -h output filtered.',
            'Current usage evaluated: 45%',
            'Script completed with return status: 0'
          ]
        },
        {
          title: 'Docker Containerization & Optimized Multi-stage Dockerfiles',
          duration: '30 mins',
          code: `FROM node:18-alpine AS builder\nWORKDIR /app\nCOPY . .\nRUN npm run build\n\nFROM nginx:alpine\nCOPY --from=builder /app/dist /usr/share/nginx/html`,
          logs: [
            'Docker: Step 1/6: FROM node:18-alpine AS builder',
            'Docker: Running npm run build compilation',
            'Docker: Copying build targets into Nginx folder',
            'Docker: Built final image size: 28MB (90% reduction)'
          ]
        },
        {
          title: 'Kubernetes Nodes, Services, Pods & ConfigMaps',
          duration: '42 mins',
          code: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: vidhura-web-app\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: frontend`,
          logs: [
            'k8s: kubectl apply -f deployment.yaml',
            'k8s: Pod deployment scheduled on worker node 2',
            'k8s: Replicas created: 3/3',
            'k8s: Service mapping online.'
          ]
        },
        {
          title: 'Infrastructure as Code (IaC) configuration using Terraform',
          duration: '38 mins',
          code: `provider "aws" {\n  region = "us-east-1"\n}\n\nresource "aws_instance" "production_node" {\n  ami           = "ami-0c55b159cbfafe1f0"\n  instance_type = "t2.medium"\n}`,
          logs: [
            'Terraform: terraform init provider plugins...',
            'Terraform: Planning resource allocation. 1 to add.',
            'Terraform: aws_instance.production_node: Creating...',
            'Terraform: Apply complete! Resources: 1 created.'
          ]
        },
        {
          title: 'Continuous Delivery with GitHub Actions & Jenkins Pipelines',
          duration: '29 mins',
          code: `name: Production CI/CD Deployment\non:\n  push:\n    branches: [ main ]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3`,
          logs: [
            'CI: Triggered by user push event on branch main',
            'CI: Setup container runner architecture',
            'CI: Executing sonar scanner review check',
            'CI: Triggering deploy callback to AWS EKS...'
          ]
        }
      ],
      flowSteps: [
        { step: '01', title: 'Live IaC Infrastructure Class', desc: 'Provision cloud nodes using Terraform live.' },
        { step: '02', title: 'Multi-Stage Docker Playback', desc: 'Review container optimization scripts.' },
        { step: '03', title: 'Interactive Shell Sandbox', desc: 'Write bash scripting tasks in active terminal.' },
        { step: '04', title: 'Continuous Integration Test', desc: 'Trigger automated CI tests on submission.' },
        { step: '05', title: 'SRE Production Mock Drill', desc: 'Troubleshoot simulated platform downtime.' }
      ]
    },
    {
      id: 'frontend',
      name: 'React & Front-End Engineering',
      tag: 'Modern Interactive Web Apps',
      icon: 'fa-brands fa-react',
      difficulty: 'Beginner Friendly',
      duration: '4 Months',
      salary: '₹3.8 - ₹12 LPA',
      shortDesc: 'Build fast, animated, and responsive web applications using modern visual frameworks.',
      techStack: ['ReactJS', 'Next.js Framework', 'TypeScript', 'Tailwind CSS', 'Redux Toolkit', 'HTML5/CSS3'],
      chapters: [
        {
          title: 'Modern JavaScript (ES6+), Async/Await & DOM manipulation',
          duration: '18 mins',
          code: `const fetchStudentsData = async (batchId) => {\n    try {\n        const response = await fetch(\`/api/batches/\${batchId}\`);\n        const result = await response.json();\n        return result.data;\n    } catch (e) {\n        console.error(e);\n    }\n};`,
          logs: [
            'Executing JavaScript module callback...',
            'HTTP Request dispatched to server API...',
            'Response resolved with HTTP Status 200',
            'Output: Returns parsed student records'
          ]
        },
        {
          title: 'React Core Hooks: useState, useEffect, useContext',
          duration: '35 mins',
          code: `import React, { useState, useEffect } from 'react';\n\nexport const StudentCard = () => {\n    const [score, setScore] = useState(100);\n    useEffect(() => {\n        console.log("Card mounted.");\n    }, []);\n    return <div className="p-4">Score: {score}</div>;\n};`,
          logs: [
            'Initializing React render lifecycle...',
            'Hook state registered for index 0 (initial value = 100)',
            'Output: Card mounted.',
            'Render tree updated.'
          ]
        },
        {
          title: 'Building Interfaces with Tailwind CSS Flex/Grid layout',
          duration: '25 mins',
          code: `<div class="grid grid-cols-1 md:grid-cols-3 gap-6 p-8 bg-slate-900 rounded-3xl shadow-premium hover:translate-y-1 transition-all duration-300">\n  <div class="flex items-center gap-4">\n    <i class="fa-solid fa-bolt"></i>\n    <h4>Fast Layouts</h4>\n  </div>\n</div>`,
          logs: [
            'Tailwind: Processing utility styles map...',
            'Inlining margin and padding utilities classes',
            'Render nodes compiled.',
            'Output: Flexbox layout rendered successfully.'
          ]
        },
        {
          title: 'Global State Management with Redux Toolkit',
          duration: '40 mins',
          code: `import { createSlice } from '@reduxjs/toolkit';\n\nconst authSlice = createSlice({\n    name: 'auth',\n    initialState: { user: null, active: false },\n    reducers: {\n        login: (state, action) => { state.user = action.payload; state.active = true; }\n    }\n});`,
          logs: [
            'Redux Store context initialized.',
            'Action payload validation check completed.',
            'Mutator slice compiled successfully.',
            'Output: Login state dispatcher active.'
          ]
        },
        {
          title: 'Next.js App Routing and Server-Side Rendering (SSR)',
          duration: '48 mins',
          code: `export default async function BatchPage({ params }) {\n    const batchDetails = await getBatchData(params.id);\n    return (\n        <main className="container">\n            <h2>{batchDetails.name}</h2>\n        </main>\n    );\n}`,
          logs: [
            'NextJS: Compiling server-side component batch page',
            'NextJS: Fetching dynamic server query dependencies...',
            'NextJS: Static HTML stream flushed to client in 22ms',
            'Hydration initialized on client side.'
          ]
        }
      ],
      flowSteps: [
        { step: '01', title: 'Live Web Component Class', desc: 'Create custom UI components with the mentor.' },
        { step: '02', title: 'Redux State Flow Playback', desc: 'Replay state store flow charts.' },
        { step: '03', title: 'Responsive CSS Coding Lab', desc: 'Perfect layouts using browser container compilers.' },
        { step: '04', title: 'NextJS Portal Deploy', desc: 'Push react bundle to production web servers.' },
        { step: '05', title: 'UI Design Mock Interview', desc: 'Review frontend portfolio design questions.' }
      ]
    }
  ];

  activeTrackId = 'java';
  isPlaying = false;
  activeChapterIndex = 0;
  playbackSpeed = '1.0x';
  playbackProgress = 35; // percentage
  playbackTime = '08:42';

  // Volume control
  isMuted = false;
  volumePercent = 80;

  // Fullscreen mockup mode
  isFullscreen = false;

  private progressInterval: any = null;

  constructor(
    private router: Router,
    private http: HttpClient,
  ) { }

  ngOnInit(): void {
    // Start progress simulation on load
    this.startProgressSimulation();
  }

  ngOnDestroy(): void {
    this.clearProgressSimulation();
  }

  get activeTrack(): Track {
    return this.tracks.find((t) => t.id === this.activeTrackId) || this.tracks[0];
  }

  get activeChapter(): Chapter {
    return this.activeTrack.chapters[this.activeChapterIndex] || this.activeTrack.chapters[0];
  }

  get activeChapterLogs(): string[] {
    const totalLogs = this.activeChapter.logs.length;
    // Dynamically show logs based on playbackProgress percentage
    if (this.playbackProgress < 20) return this.activeChapter.logs.slice(0, 1);
    if (this.playbackProgress < 45) return this.activeChapter.logs.slice(0, 2);
    if (this.playbackProgress < 75) return this.activeChapter.logs.slice(0, 3);
    if (this.playbackProgress < 95) return this.activeChapter.logs.slice(0, 4);
    return this.activeChapter.logs;
  }

  selectTrack(trackId: string): void {
    this.activeTrackId = trackId;
    this.activeChapterIndex = 0;
    this.playbackProgress = 12;
    this.playbackTime = '02:15';
    this.isPlaying = false;
    this.startProgressSimulation();
  }

  togglePlay(): void {
    this.isPlaying = !this.isPlaying;
  }

  selectChapter(index: number): void {
    this.activeChapterIndex = index;
    this.playbackProgress = 0;
    this.playbackTime = '00:00';
    this.isPlaying = true;
  }

  setSpeed(speed: string): void {
    this.playbackSpeed = speed;
    if (this.isPlaying) {
      this.startProgressSimulation(); // Reinitialize timer interval with new speed configuration
    }
  }

  toggleMute(): void {
    this.isMuted = !this.isMuted;
  }

  toggleFullscreen(): void {
    this.isFullscreen = !this.isFullscreen;
  }

  seekPlayback(event: MouseEvent): void {
    const container = event.currentTarget as HTMLElement;
    const rect = container.getBoundingClientRect();
    const clickX = event.clientX - rect.left;
    const width = rect.width;
    const newPercent = Math.round((clickX / width) * 100);
    this.playbackProgress = Math.max(0, Math.min(100, newPercent));

    // Calculate time based on progress
    const minutes = Math.floor((this.playbackProgress * 15) / 100);
    const seconds = Math.floor(((this.playbackProgress * 15) % 100) * 0.6);
    const padM = String(minutes).padStart(2, '0');
    const padS = String(seconds).padStart(2, '0');
    this.playbackTime = `${padM}:${padS}`;
  }

  getHighlightedCode(): string {
    let code = this.activeChapter.code;
    if (!code) return '';

    // First escape HTML entities
    code = code
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    // Keywords to highlight
    const keywords = [
      'public', 'private', 'protected', 'class', 'interface', 'extends', 'implements',
      'static', 'void', 'int', 'double', 'float', 'boolean', 'String', 'Long',
      'def', 'for', 'in', 'import', 'as', 'from', 'return', 'try', 'catch', 'except',
      'const', 'let', 'var', 'await', 'async', 'if', 'else', 'provider', 'resource'
    ];

    // Highlight strings first (single/double quotes)
    code = code.replace(/(["'`])(.*?)\1/g, '<span class="code-string">$1$2$1</span>');

    // Highlight keywords
    const keywordRegex = new RegExp(`\\b(${keywords.join('|')})\\b`, 'g');
    code = code.replace(keywordRegex, '<span class="code-keyword">$1</span>');

    // Highlight annotations (e.g. @RestController, @Entity, @Table, @Id, @GeneratedValue, @GetMapping, @RequestMapping)
    code = code.replace(/(@\w+)/g, '<span class="code-annotation">$1</span>');

    // Highlight comments starting with // or #
    code = code.replace(/(\/\/.*|#.*)$/gm, '<span class="code-comment">$1</span>');

    return code;
  }

  goToCheckout(): void {
    // Dynamically retrieve all courses and resolve parameters from database
    this.http.get<any>(`${environment.apiUrl}/api/public/courses`).pipe(
      catchError(() => of({ data: [] }))
    ).subscribe((res) => {
      const coursesList = res?.data || [];
      const trackId = this.activeTrackId;
      
      // Match track keyword in database titles
      const matchedCourse = coursesList.find((course: any) => {
        const title = (course.title || '').toLowerCase();
        const code = (course.code || '').toLowerCase();
        if (trackId === 'java') return title.includes('java') || code.includes('java');
        if (trackId === 'python') return title.includes('python') || code.includes('python');
        if (trackId === 'devops') return title.includes('devops') || title.includes('cloud') || code.includes('devops');
        if (trackId === 'frontend') return title.includes('react') || title.includes('front') || code.includes('react');
        return false;
      });

      if (matchedCourse) {
        // Fetch active batch to make checkout fully correct
        this.http.get<any>(`${environment.apiUrl}/api/lms/batches/course/${matchedCourse.id}/active`).pipe(
          catchError(() => of({ data: null }))
        ).subscribe((batchRes) => {
          const activeBatch = batchRes?.data || null;
          this.router.navigate(['/checkout'], {
            queryParams: {
              courseId: matchedCourse.id,
              course: matchedCourse.title,
              amount: matchedCourse.price,
              batchId: activeBatch ? activeBatch.id : null,
              batch: activeBatch ? activeBatch.name : null
            }
          });
        });
      } else {
        // Fallback catalog routing if course isn't found in DB
        this.router.navigate(['/courses']);
      }
    });
  }

  private startProgressSimulation(): void {
    this.clearProgressSimulation();

    // Map speed to timer delay (1.0x = 1000ms, 1.25x = 800ms, 1.5x = 666ms, 2.0x = 500ms)
    let intervalDelay = 1000;
    if (this.playbackSpeed === '1.25x') intervalDelay = 800;
    else if (this.playbackSpeed === '1.5x') intervalDelay = 666;
    else if (this.playbackSpeed === '2.0x') intervalDelay = 500;

    this.progressInterval = setInterval(() => {
      if (this.isPlaying) {
        this.playbackProgress += 1;
        if (this.playbackProgress > 100) {
          this.playbackProgress = 0;
          this.activeChapterIndex = (this.activeChapterIndex + 1) % this.activeTrack.chapters.length;
        }

        // Simulating timer change
        const minutes = Math.floor((this.playbackProgress * 15) / 100);
        const seconds = Math.floor(((this.playbackProgress * 15) % 100) * 0.6);
        const padM = String(minutes).padStart(2, '0');
        const padS = String(seconds).padStart(2, '0');
        this.playbackTime = `${padM}:${padS}`;
      }
    }, intervalDelay);
  }

  private clearProgressSimulation(): void {
    if (this.progressInterval) {
      clearInterval(this.progressInterval);
      this.progressInterval = null;
    }
  }
}
